### ISSUE TITLE
chore: setup revapi to detect compatibility issues

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1023]
http://revapi.org/
https://github.com/revapi/revapi

**Comment by monperrus** [comment]
see http://massol.myxwiki.org/xwiki/bin/view/Blog/ByeByeCLIRRWelcomeRevapi

**Comment by surli** [comment]
Just include revapi in the project (see https://github.com/surli/spoon/commit/d3a18d8223476fd29410459a475f0415c4ca5421) including all package _spoon.*_ and excluding all package containing _test_ in the name. 

But when I analyze the project I have a very long list of problem, because of changes done between Spoon 5.4.0 and 5.5.0 (see https://gist.github.com/surli/422d9acaa4992bf79e097dcc5ccbeea5) then which classes or packages should we analyze exactly?

**Comment by surli** [comment]
Check to ignore addMethod if the method just have a new annotation or new Javadoc.
Ignore all *Impl classes. 
Check if it detects backward compatible interface changes (see ImportScanner interface change for example).
Change config to compare with the last SNAPSHOT release of the night.

**Comment by surli** [comment]
Asked revapi guys if the issue is supported yet or not: https://github.com/revapi/revapi/issues/54

**Comment by surli** [comment]
New version of revapi-maven-plugin has been released then I'm starting to setup a configuration to use it (see https://github.com/surli/spoon/commit/0dbfe793d158d388dcbcc61537e202d41ccffd86)
However there's still some issues regarding our hierarchies, e.g. an added method in CtElement will throw errors for all inherited interfaces which means a lot... I opened an issue to discuss about that on revapi: https://github.com/revapi/revapi/issues/62.

Still it could be good to discuss here what kind of configuration we do want for revapi in Spoon.
Do we need to configure Travis build to make different comparison given it's a PR or a push? Do we need to make specific check when releasing a Snapshot during the night? Or when doing a new release to specify the right version of the release? What do we need to ignore in the API checks?

**Comment by metlos** [comment]
I'm trying to build spoon from https://github.com/surli/spoon/tree/addRevAPI. I added the snapshot repo http://spoon.gforge.inria.fr/repositories/snapshots/ but I'm still getting 
```
[ERROR] Failed to execute goal on project spoon-core: Could not resolve dependencies for project fr.inria.gforge.spoon:spoon-core:jar:5.6.0-SNAPSHOT: Could not find artifact commons-io:commons-io:jar:2.6-SNAPSHOT
```

Is there anything I missed to properly build spoon? I'd like to take a proper look at https://github.com/revapi/revapi/issues/62 in your environment, because theoretically, Revapi shouldn't report stuff that's reported elsewhere - https://github.com/revapi/revapi/blob/master/revapi-java/src/main/java/org/revapi/java/JavaElementDifferenceAnalyzer.java#L485

**Comment by metlos** [comment]
ok, apache snapshots repo did the trick :)

**Comment by surli** [comment]
Look how we can generate a report from revapi and integrates it into the PR as comment (see coverage report)
