### ISSUE TITLE
Release 5.5.0 planned for Wednesday Jan 11th 2017 

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1081]
Hi everyone,

we plan to do a new minor release of Spoon next wednesday.
I'll give info when the release will be done.

**Comment by tdurieux** [comment]
# Changelog

# New feature

* New query architecture with support for Java8 queries. (PR: #1018)
* Allow spoon to do static imports for methods and fields. (PR: #1040)
* Interface to Exclude Compilation Units From CtModel. (PR: #1037)
* **API** : Add CtTypeMember.getTopLevelType(). (PR: #1004)
* **CoreFactory**
  * Add create(Class) so as to create elements by reflection. (PR: #949)
  * Add create(Class) so as to create elements by reflection. (PR: #949)
* **evaluation** : Simplify classes based on static evaluation (first support). (PR: #1003)
* **filter** : Compute filtered types by reflection from parameter of method matches. (PR: #1015)
* **getDeclaredOrInheritedField** : Add CtTypeInformation.getDeclaredOrInheritedField(String fieldName). (PR: #967)
* **model** : Add interface CtBodyHolder. (PR: #943)
* **position** : Improve the element position. (PR: #984)
* **snippet** : Add support for compiling statements with return. (PR: #947)


# Fixes

* **DefaultJavaPrettyPrinted** : Fix bug when printing implicit accesses to static fields in autoimport. (Issue: #914) (PR: #913)
* **JDTBasedSpoonCompiler** : Fix annotation bug when templates are used. (Issue: #921) (PR: #934)
* Fixed name of test class. (PR: #1037)
* Fixed formatting. (PR: #1037)
* Generate expected EOL even on Windows. (PR: #977)
* Fix inconsistencies between interface contract and double implementations of getAllExecutables. (PR: #1019)
* Clean exception when Spoon is given a wrong path for input resource. (PR: #1057)
* No exception when writing to log. (PR: #920)
* Removes unused imports. (PR: #988)
* Test: APITest.testSetterInNodes() was not testing anything . fix #972. (PR: #1022)
* **SignaturePrinter** : Overrides visitCtAnnotationMethod in SignaturePrinter. (PR: #1030)
* **ThisAccess**
  * Shorter this access. (PR: #1031)
  * The type access associated to a this must be the type containing the this. (PR: #1008)
* **access path** : Fix regression with type parameters in access paths. (PR: #1007)
* **annotations** : Fix Dropwazrd regression by fixing substituteAnnotation. (PR: #1032)
* **array** : The qualified name of an array is not java.lang.reflect.Array. (PR: #995)
* **clone** : Clone preserves comments and implicitness. (PR: #1028)
* **comment** : Fixes pretty-printing bug for inline arrays with comments. (Issue: #911) (PR: #912)
* **comments**
  * Add support of comments in snippets. (PR: #930)
  * Handle stacked comments in package-info.java. (PR: #1011)
  * Fix a bug concerning multiple comments before a catch block. (PR: #1074)
* **enum** : GetAllMethods also returns the methods of Enum. (PR: #1016)
* **equal**
  * Actual type references must be part of equality. (PR: #997)
  * Regenerate EqualVisitor based on new Scanner, which fixes a number of bugs incl. #978. (Issue: #978) (PR: #993)
* **getTypeDeclaration**
  * First lookup in sources, then in classpath. (PR: #962)
  * GetTypeDeclaration('?') should point to Object. (PR: #973)
* **import** : Correct interplay between fully-qualified types and variable names . (PR: #1026)
* **imports**
  * Fix a static import bug, ripple of adb2fd7420b3bf01e696be87f4791759bfb6de53. (PR: #1060)
  * Fix regressions with static imports and inner classes or enums. (PR: #1048)
* **importscanner** : Fix regression in fuly-qualified mode. (PR: #1052)
* **isAssignableFrom** : Deprecate isAssignableFrom that is totally confusing, and for which there is an alternative. (PR: #948)
* **isSubtypeOf** : Spoon can resolve anonymous references. (PR: #953)
* **launcher** : Easy way to parse a complete class with package. (PR: #982)
* **log** : Filter out some JDT errors in noclasspath. (Issue: #788) (PR: #926)
* **model**
  * Fix NPE when compilation units array contains null elements. (Issue: #551) (PR: #928)
  * Complex access paths for types with visibility are now correctly handled. (PR: #974)
* **newinstance** : Forces usage of the newest version of the class. (PR: #909)
* **parent** : Stops furious useless exceptions. (PR: #963)
* **performance**
  * Keep shadow classes. (Issue: #867) (PR: #898)
  * Improves performance of VirtualFolder.getAllFiles() and getSubFolders(). (Issue: #916) (PR: #915)
* **precompile** : Specifies and fixes precompile option. (PR: #923)
* **pretty-print**
  * Fix pretty-printing of 'this' access for inner classes. (PR: #1061)
  * The annotation values are now pretty-printed in the original order. (PR: #1067)
* **prettyprint** : Parentheses are missing when pretty-pretting some ternary expressions. (PR: #927)
* **scanner**
  * Add missing scan properties based on a new powerful specification. (PR: #966)
  * Add missing scan properties based on a new powerful specification. (PR: #966)
* **serialization** : Fix serialization issue in Factory. (PR: #955)
* **shadow** : No ClassNotFoundException when building shadow classes by reflection. (PR: #1012)
* **subtype** : Removes CtTypeImpl#isSubtypeOf that is wrong and anyway overridden by all subclasses. (PR: #954)
* **template** : Check that Template is on source path of builder. (PR: #976)
* **test**
  * Fixes OS-dependent path in LauncherTest. (PR: #919)
  * Much stronger contracts for setter spec and tests. (PR: #975)


# Documentation

* Fix broken link. (PR: #1016)
* Adds adt poster and InDesign source. (PR: #1051)
* Fix markdown issue in code_elements.md. (PR: #1016)
* Add --noclasspath for reducing first-usage friction. (PR: #1016)
* Improve template documentation. (PR: #1068)
* Improve navigability and first contact. (PR: #1016)
* Improve readability and wording of doc/comments.md. (PR: #1079)
* Adds doc about constructor calls and the associated reference. (PR: #994)
* Clarifies responsibility of CtNamedElement. (PR: #1062)
* Adds documentation for explaining the code elements. (PR: #922)
* **SignaturePrinter** : Improves doc of SignaturePrinter. (PR: #987)
* **info** : Fix broken link to mailing list. (PR: #1003)


# Refactoring

* **classloader** : Adds test for classloader. (PR: #897)
* **printerContext** : Assure correct restore of state. (PR: #999)
* **processingmanager** : Removes duplicated code, improves readability. (PR: #1054)
* Remove code duplication and fix inconsistencies of class Substitution. (PR: #992)
* Removes dead code. (PR: #989)
* Check everywhere that Template is on source path of builder. (PR: #979)
* Removes old unseless code. (PR: #983)
* Remove unused printer code of visitCtCatchVariable. (PR: #965)
* JDTBatchCompiler arg.sources not needed. (PR: #958)
* Regenerate files with short this for future clean diffs. (PR: #1039)
* Avoid creation of JDT hacking TMP files. (PR: #944)
* JDTBatchCompiler.getUnits()  parameter not required anymore. (PR: #942)
* Remove old unmaintained/broken code. (PR: #937)
* Improves JDTCommentBuilder. (PR: #924)
* Removes duplicated code. (PR: #936)
* Remove unused imports. (PR: #935)
* Reuse existing CU in JDTBatchCompiler.getUnits(). (PR: #933)
* Introduce JDTBasedSpoonCompiler.buildModel to remove code duplication. (PR: #931)
* Same algorithm for building sources, templates and snippet. (PR: #946)


# Performance

* Cache inputClassLoader corresponding to sourceClasspath. (PR: #990)
* Improve performance of FindCommentParentScanner. (PR: #917)


# Tests

* Add tests and doc for template engine. (PR: #1072)
* Add coverage for templates (and unify API thanks to this). (PR: #1049)
* Add test for method parameter templating. (PR: #1064)
* Reduces I/O footprint (and found two IO bugs on the way). (PR: #969)
* One test was not named correctly, hence was not run by Maven in CI, hiding a bug. (PR: #1036)
* Add missing @Test. (PR: #950)
* Update CompilationTest to match latest compiler changes. (PR: #940)
* Add a test to check if TemplateMatcher can match two equivalent snippets. (PR: #1059)
* Remove unused imports. (PR: #941)
* **ParentContractTest** : Improves contract about setting parents. (PR: #956)
* **VisitorPartialEvaluator** : Add tests for VisitorPartialEvaluator. (PR: #939)
* **metamodel** : Enforce the package design of the metamodel. (PR: #945)
* **replacevisitor** : Add a strong test and fix many bugs accordingly. (PR: #957)
* **template** : Add test for super interface templates. (PR: #1020)
* **templatematcher** : Add a new Junit test and dynamic assertion for TemplateMatcher. (PR: #1034)
* **superClass** : Adds test that verifies the compilation of complex superclass references that use access paths with tricky visibility. (PR: #971)


# Other

* **jenkins** : Purge local repository of all Spoon snapshots. (PR: #1065)
* Change eclipse jdt core dependency now depends on Maven central only. (PR: #1063)
* Update version of spoon-maven-plugin. (PR: #906)
* **build.sh** : Update minimum version to fix problem with repo.eclipse.org. (PR: #1003)
* **coverage** : Update coveralls version. (PR: #1001)
* **release** : Update version number in documentation. (PR: #907)


# Unknown

* Fixes a typo in doc/gradle.md. (PR: #1078)
* Renamed label from units to unitLoop. (PR: #1037)
* Remove dependency to CompilationUnitDeclaration. (PR: #1037)
* Merge remote-tracking branch 'upstream/master' into fix985. (PR: #1037)
* Added a test for new compilation unit filter. (PR: #1037)
* Added license note to CompilationUnitFilter. (PR: #1037)
* Use filter to exclude instead of accapt units. (PR: #1037)
* Deprecate reference filtering that is now handled by standard element filtering. (PR: #1013)
* We must always have a source + exception handling. (PR: #996)
* Added an interface used to filter particular CompilationUnitDeclaraions. (PR: #1037)

**Comment by retuxx** [comment]
Looks like a big update. Thank you to all contributors!

**Comment by surli** [comment]
Done yesterday https://github.com/INRIA/spoon/releases/tag/spoon-core-5.5.0
