### ISSUE TITLE
chore: gakoci spoon-master-docker jobs return wrong value

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1179]

**Comment by monperrus** [comment]
it seems because the tests take now more than the 10 minutes timeout of gakoci.

    Total time: 14:51 min

Maybe because the server does the librepair stuff as well.

Action: I've increased the timeout to 20 minutes

Sidenote: Gakoci should set a special status when this happens: https://github.com/monperrus/gakoci/issues/4
