### ISSUE TITLE
Inconsistent executable signature on generic types 

### ISSUE THREAD

**Issue by Tallic** [INRIA/spoon#1483]
Given 

 ```Java
List<String> strings = new ArrayList<String>
strings.add("foo")
```
 and the resulting ctInvocation on the executable `Java.util.ArrayList#add(..)`,
spoon will return different signatures depending on the call chain of the signature retrieval:
1. `ctInvocation.executable.signature` -> `java.util.ArrayList#add(E)`
2. `ctInvocation.executable.executableDeclaration.signature` -> `boolean add(java.lang.Object)`
3. `ctInvocation.executable.executableDeclaration.reference.signature` -> `java.util.ArrayList#add(java.lang.Object)`

where 1 is an exec reference, 2 an exec declaration and 3 an exec reference again.

1 and 3 are inconsistent and should probably result in the object signature, not the generic one (like case 3).

**Comment by pvojtechovsky** [comment]
Hi Tallic,

I do not think it is a bug. The java generics are there to generate different method signatures depending on generic type arguments. So it is correct that case 1) and 3) are different signatures, because they have different generic type arguments.
The difference in format of case 2) and 1) (or 3)), is probably intentional, because declaration of method and reference to that method are different things.

Why do you need same signatures? Why do you compare signatures? What problem are you solving?

**Comment by Tallic** [comment]
Hi there,
case 2 is not the problem since it is not a reference.

Rethinking I would expect something like
1. is the reference from the invocations point of view (i.e., proper parameterized e.g., `java.util.ArrayList#add(java.lang.String)`)
2. the declaration itself
3. the reference from the declarations point of view (i.e., generic parameters e.g., `java.util.ArrayList#add(E)` or the object version as it is also true to some extent

But then again, I might misunderstand the spoon reference model.
I extract a high-level ASG from the spoon model up to method level hence the need for signatures.

**Comment by pvojtechovsky** [comment]
I understand and agree with you. The generics were added to spoon later, so it looks like nobody needed method signatures for generic methods till now.

to 1) the generics should be replaced with actual types - so it should look same like you suggested in Your last comment

to 2) it is question how the declaration should look like. We should not print generic type arguments there, because they can come from method or any parent enclosing type. So it probably makes sense to replace generic types by their type erasures.

to 3) the generics should be replaced with type erasures too.

So if I understand it well, then only case 1) has to be changed. Others already works as expected.

@monperrus or others WDYT?

**Comment by Tallic** [comment]
Hmmm avoiding type erasure might be preferable from an analysis capability standpoint:
* `java.lang.Object` is the supertype of all classes hence it is always true but seldom useful.
* Using a type parameter `E` may be ambiguous as the declaring context is initially unknown, however, the real source can be easily found via `CtTypeParameterReference<?>.getDeclaration() : CtTypeParameter`.
