### ISSUE TITLE
CompilationUnitImpl: getOriginalSourceCode() always uses the platform's default charset.

### ISSUE THREAD

**Issue by msteinbeck** [INRIA/spoon#1497]
I think `getOriginalSourceCode()` should try to guess the encoding before creating a String. I did some research and found the following libraries: [juniversalchardet](https://github.com/albfernandez/juniversalchardet) and [ICU4J](https://wiki.eclipse.org/ICU4J). Maybe combining them might be useful. That is,  `getOriginalSourceCode()` tries to guess the encoding using juniversalchardet at first and if it wasn't able to find an appropriate encoding, uses ICU4J afterwards. What do you think?

**Comment by surli** [comment]
> I think getOriginalSourceCode() should try to guess the encoding before creating a String.

It looks overkilling to me to try guessing the encoding of a project inside Spoon: especially since we have a encoding argument for the launcher. 
However I agree with you that we certainly should use the encoding argument in `getOriginalSourceCode`. 
I propose to refactor the `Environment` to add the encoding information (retrieve from the launcher argument), and then to use it in `getOriginalSourceCode`. 
Then, if you have a lot of projects with different encodings you can use your proposed libraries before launching Spoon to detect encoding and pass it to Spoon as argument. 

WDYT?

**Comment by msteinbeck** [comment]
> Then, if you have a lot of projects with different encodings you can use your proposed libraries before launching Spoon to detect encoding and pass it to Spoon as argument.

I'm fine with this proposal.
