### ISSUE TITLE
Cannot get Class<?> from annotation in spoon processor

### ISSUE THREAD

**Issue by gnom7** [INRIA/spoon#1590]
Hello, I have tested it with spoon 5.3.0 and 5.7.0
I'm trying to process (with spoon processor) annotation that provides me with java `Class<?>` object.
When that type from annotation is in classpath where spoon was launched from or in spoon's `source classpath` all works well.
But when it is placed with `input sources` for spoon to process, spoon cannot create reference to that type (it (`spoon.support.reflect.reference.CtTypeReferenceImpl#findClass`) searches only in `URLClassLoader` created from provided `sources classpath`, although spoon `Environment` has necessary type (from `input sources`) and actually can resolve it).
Please, any help

UPD
I have created sample <a target="_blank" href="https://github.com/gnom7/spoon-bug">project</a> that demonstrates my issue.
`processor` module contains annotation and processor for it, it will be our `sources classpath` (as source code uses annotation).
`main` module depends on `processor` and runs code transformation.
`com` folder in project's root contains sources to process.
After project build, run `Main` class in `main` module and look at the `bug` module's `target` where spooned sources will be placed. `K1.java` should have method that returns `com.K2.class`, but now it has empty body. Then if you copy K2 class to `processor` module (so it appears in the sources classpath) or to the `main` module, spoon processes sources well.
Also, is there any built in way to fail spoon's caller process with exception when exception occurres inside spoon (to fail-fast if spoon is likely to generate garbage), i.e. force `Launcher` to rethrow its inner exception?

**Comment by surli** [comment]
Hi @gnom7 

thanks for creating a project example, it really helps.
In fact, every sources you put in `input sources` never reaches the classloader with Spoon: so your two java classes are available in Spoon model, but not in the classloader. 

Then your problem here appends in `annotation.clazz()` which throws a NPE because it cannot resolve the class name. I have to investigate a bit more, because it happens in `CtAnnotation` class of Spoon so maybe it's a bug inside Spoon. 

In the mean time you can solve your problem in two ways:
   1. Compile your java classes you use and put them into the classpath: you already find it fixes the issue, it's the easiest way to avoid the problem
   2. Instead of using an annotation with a Class field, use a String field, you'll be able to create an annotation like:

```java
@Annotation(clazz = "com.K2")
```

Then you can access the class directly from the model in AnnotationProcessor:
```java
CtType<?> ctClazz = getFactory().Type().get(annotation.clazz());
```
I understand the latter solution is not really satisfactory as you loose the type checking in the annotation...

**Comment by gnom7** [comment]
Thank you @surli, I'll keep in mind those two solutions.
I'm not sure to understand how exactly `spoon` works under the hood, so my question may be confusing - why cannot we search in whole model, rather than in the provided `classpath` only?

**Comment by surli** [comment]
> why cannot we search in whole model, rather than in the provided classpath only?

Hmmm actually you can search in the whole model, actually it's rather recommended!
What kind of search don't you manage to do?

Oh by the way about that:
> Also, is there any built in way to fail spoon's caller process with exception when exception occurres inside spoon (to fail-fast if spoon is likely to generate garbage), i.e. force Launcher to rethrow its inner exception?

We fix bugs in latter version of Spoon, if you use the 5.9.0 you will see the processor crash because of the NPE. 
Else you can just throw a SpoonException when you detect a problem.

**Comment by gnom7** [comment]
> What kind of search don't you manage to do?

I talk about search that `spoon` performs when I call `annotation.clazz()` in the `spoon.support.reflect.reference.CtTypeReferenceImpl#findClass` method. If it is possible to perform search in the whole model than that issue will be solved.

> We fix bugs in latter version of Spoon, if you use the 5.9.0 you will see the processor crash because of the NPE.
> Else you can just throw a SpoonException when you detect a problem.

Thanks. That applies only to `NPE` and `SpoonException`?

**Comment by gnom7** [comment]
OK, it seems that I understand why we cannot search for `Class<?>` in the `spoon`'s model.
And if I understand that right I see one workaround is to try to compile passed sources and if that succeeds add additional path to the classloader or the whole new classloader to ultimately search `Class<?>` from it and only then throw `SpoonClassNotFoundException`.
Or maybe there is more advanced way to construct `Class<?>` object directly, having `spoon` AST?

**Comment by surli** [comment]
Sorry @gnom7 apparently I forget to answer you on this one!

>  talk about search that spoon performs in the spoon.support.reflect.reference.CtTypeReferenceImpl#findClass method when I call annotation.clazz(). If it is possible to perform search in the whole model in that exactly spoon's method, rather than in the classpath only, than this issue will be resolved.

Actually `findClass` return a `Class` object, not `a CtClass` as in Spoon model, so when we call findClass we look for a class which is compiled and available in the classpath. You have to remind that Spoon is used to transform source code: the model represents the state of a project based on its source code, not on its compiled classes. Then we generally cannot reached the .class of `CtClass` which is included in the model itself. 

I hope this answers your question. I close this issue for now, don't hesitate to reopen a new one if you have new question or to continue the discussion here if you prefer.

**Comment by gnom7** [comment]
Thanks for the help @surli 
Am I right that we only have those workarounds?

>     1. Compile your java classes you use and put them into the classpath
>     2. Instead of using an annotation with a Class field, use a String field

**Comment by surli** [comment]
> Am I right that we only have those workarounds?

Those are the only ones I can see.
