### ISSUE TITLE
Problem when importing annotation from a dependency

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#1648]
When trying to parse the class below, the field
```java
package mypackage;
import org.springframework.web.bind.annotation.*;

@RestController
class myObject {
    public myObject() {}

}
```
is parsed as
```java 
package mypackage;

@RestController
class myObject {
    public myObject() {
    }
}
```
When exploring the model the annotation `@RestController` has type `mypackage.RestController`.

Spoon was called as :
```java
Launcher launcher = new Launcher();
launcher.addInputResource(srcDir.getPath());
launcher.getEnvironment().setAutoImports(true);
launcher.getEnvironment().setNoClasspath(true);
launcher.getEnvironment().setComplianceLevel(8);
launcher.buildModel();

CtModel model = launcher.getModel();
```

**Comment by surli** [comment]
Hi @nharrand 

you're working in `noClassPath` mode: it means, Spoon will try to infer all information from the model, even if all libraries are not given to it. 

Here, I assume that `@RestController` is imported from your starred import, but Spoon cannot infer it: it might also be in the same package. In this case, it choses the simple case, meaning "it's in the same package". That's why you have the type `mypackage.RestController`. 

To avoid that you can either avoid using starred imports (with an explicit import, Spoon would have take the right type) or pass the library to Spoon.

Hope that helps.

**Comment by nharrand** [comment]
Ok,
I was trying to load only the minimum number of class to be efficient. 
The thing is I'm not working with this annotation, I'm only trying to modify something else in the class, but when I write the results, imports disappear. I realize now that,  as I don't load anything else, the problem is not solvable for spoon.
Is there a way not to alter the imports of a class?

**Comment by surli** [comment]
> Is there a way not to alter the imports of a class?

We do not manage the star imports in Spoon. 
It's something we have to work on.

**Comment by surli** [comment]
I close this issue. Note that I opened a discussion to improve imports in Spoon #1650. I can't provide any date for releasing it, but we will work on that :)

**Comment by nharrand** [comment]
Of course. Thanks for the help anyway!
