### ISSUE TITLE
Revapi is broken

### ISSUE THREAD

**Issue by tdurieux** [INRIA/spoon#1663]
Revapi provides currently useless information

**Comment by monperrus** [comment]
yes it's borken. note that the Revapi job does not depend on Java9. the problem is somewhere else

**Comment by monperrus** [comment]
https://github.com/revapi/revapi/issues/100

**Comment by monperrus** [comment]
https://github.com/revapi/revapi/issues/100 is fixed

now we have https://github.com/revapi/revapi/issues/101

**Comment by monperrus** [comment]
Summary of experiments:

- it's not because of a Maven version problem (same problem with 3.3.9 and 3.5)
- it's not because of OpenJDK/OracleJDK  (same problem with both)
- it's not because of Java9 runtime (JVM9 not used in snapshot building or revapi)
- it's not because of the JDK9 support commit (the previous commit also fails)
- it's not because of the new version of JDT-core (the previous version also fails)
- the latest version of Revapi still has the same problem

Other options to explore:

- the difference between the Snapshot building env (Jenkins/sos-builder01) and the Revapi check (spoon3r VM)
- the Jacoco version change
- the animal sniffer removal

**Comment by monperrus** [comment]
old: method java.util.ArrayList Main::handleBootclasspath(ArrayList, java.lang.String) @ JDTBatchCompiler
    new: method java.util.ArrayList<String> Main::handleBootclasspath(ArrayList<String>, java.lang.String) @ JDTBatchCompiler

The difference is only in the generics.

Asked https://github.com/revapi/revapi/issues/102

**Comment by pvojtechovsky** [comment]
May be it would be possible to black-list a REVAPI messages, which can be safely ignored?

**Comment by monperrus** [comment]
as a workaround yes

**Comment by monperrus** [comment]
closed per #1665
