### ISSUE TITLE
chore: add a jenkins job to run PIT Descartes

### ISSUE THREAD

**Issue by surli** [INRIA/spoon#1819]
In order to obtain automatically a diagnosis related to badly tested methods (see #1818) we should create a Jenkins job with PIT descartes: https://github.com/STAMP-project/pitest-descartes

**Comment by surli** [comment]
Done in https://ci.inria.fr/sos/job/spoon-pit-descartes/

**Comment by monperrus** [comment]
Cool! I guess this job will take a long time.

**Comment by Rohitesh-Kumar-Jain** [comment]
Hi @surli, 

> Done in https://ci.inria.fr/sos/job/spoon-pit-descartes/

This link isn't working (404). 

Is there any Jenkins job/or any other method that automatically generates badly tested methods?

**Comment by monperrus** [comment]
Running https://github.com/STAMP-project/pitest-descartes directly in command line.

**Comment by Rohitesh-Kumar-Jain** [comment]
@monperrus thanks, should I also update [this list](https://github.com/STAMP-project/descartes-experiments/blob/master/actionable-hints/spoon/index.md) after generating badly tested methods? 

I tried running https://github.com/STAMP-project/pitest-descartes by first adding plugin in the pom.xml file and running the command `mvn clean package org.pitest:pitest-maven:mutationCoverage`, but it is generating error: 



[ERROR] Failed to execute goal org.pitest:pitest-maven:1.6.4:mutationCoverage (default-cli) on project spoon-core: Execution default-cli of goal org.pitest:pitest-maven:1.6.4:mutationCoverage failed: 6 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException



I am not sure but feel that this is caused by a failing test, but when I am running `mvn test
` it shows BUILD success with : Tests run: 1886, Failures: 0, Errors: 0, Skipped: 13

I would be glad if you may help me rectify this error : )

**Comment by monperrus** [comment]
> [ERROR] Failed to execute goal org.pitest:pitest-maven:1.6.4:mutationCoverage (default-cli) on project  spoon-core: Execution default-cli of goal org.pitest:pitest-maven:1.6.4:mutationCoverage failed: 6 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.

This may be a bug in Descartes, to be fixed, see https://github.com/STAMP-project/pitest-descartes/issues/117

> @monperrus thanks, should I also update this list after generating badly tested methods?

yes, feel free to PR on it regularly to keep track of your test improvements.
