### ISSUE TITLE
feat: add method getTopDefinitions() to identify first signature in superclass/superinterface

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#1821]
question: bug in getOverridingExecutable? sometimes the overridden method is not found

See https://github.com/monperrus/spoon/commit/774e71939cff382aac2c2193063b3029117f9f1f

@pvojtechovsky this seems to be in parameter adaptation, could you have a look at it? Thanks!

**Comment by pvojtechovsky** [comment]
The first failure is on
```java
class CtScanner implements CtVisitor {
public <T> void visitCtAnnotationMethod(spoon.reflect.declaration.CtAnnotationMethod<T> annotationMethod) {...}
}
```
and it fails, because `CtExecutableReferenceImpl#getOverridingExecutable` looks in super classes only, it completely ignores super interfaces. It is like that since NOV 2007. May be it was correct for Java 5, but later Override can be applied to interface methods too. So may be Spoon needs a change in API of this method, because since Java 6, such method can return LIST of overriden methods in result of `getOverridingExecutable`.

WDYT?

**Comment by monperrus** [comment]
Interesting, it means that getOverridingExecutable gives the super implementation but not the super declaration. I'll do a PR to update the documentation.

What about creating a new method `getTopDefinition()`? (other names may be `getTopSignature()` or `getFirstDefinition()`?

The signature could be

`Collection<CtMethod> CtMethod#getTopDefinition()`
or
`Collection<CtExecutableReference> CtMethod#getTopDefinition()`

WDYT?

**Comment by pvojtechovsky** [comment]
where would that `getTopDefinition` algorithm search in?
A) in direct implemening interfaces only
B) in all implementing intefaces recursively 
C) in superClasses + A) or B)
D) ?

May be we should not add new method on CtExecutableReference - because there is many possibilities what client might need, but we should instead implement new mapping function `MethodDeclarationFunction`, which might be configurable like
* checkInterfaces(boolean)

Then client can call
```java
CtExecutableReference eref = ...
eref.map(new MethodDeclarationFunction().checkInterfaces(true)).first()
```
to get first definition of method in some interface.

WDYT?

**Comment by monperrus** [comment]
> May be we should not add new method on CtExecutableReference 
yes, I also prefer to have this new method only in CtMethod

**Comment by monperrus** [comment]
> where would that |getTopDefinition| algorithm search in?
> A) in direct implemening interfaces only
> B) in all implementing intefaces recursively
> C) in superClasses + A) or B)
> D) ?
>
I would say C), it makes the most sense to me.
