### ISSUE TITLE
getOverriddingExecutable() is missing annotations

### ISSUE THREAD

**Issue by Eric-W0** [INRIA/spoon#1892]
Hi,

I'm analyzing this source:

    static class FunctionOverriddingBase {

        @Function
        int f() {
            return 1;
        }
    }

    static class FunctionOverriddingDerived extends FunctionOverriddingBase {

        @Override
        @Action
        int f() {
            return 2;
        }
    }

At some point within an annotation processor, I got a `executable` of type `CtExecutable` referring to `FunctionOverriddingDerived::f`. The call `executable.getReference().getOverriddingExecutable().hasAnnotation(Function.class)` gives me a surprising `false`.

It appears while debugging that it would return the correct result if I'm calling `executable.getReference().getOverriddingExecutable().getDeclaration().hasAnnotation(Function.class)`, but I find it odd that the reference cannot give me that result directly. Especially if the the source to `FunctionOverriddingBase` is not within Spoon's scope.

Strangely enough, I saw that there's a commented out version of `CtExecutableReferenceImpl::hasAnnotation` that looks correct (using Java introspection to get the result). Any reason why it's been commented out?

Thank you for your great work anyway, I got much further with Spoon that I would have had with anything else. Encore merci :-)

**Comment by pvojtechovsky** [comment]
Hi Eric!
I understand your issue. The relation of CtReference/CtElement is not ideal - sometime confusing.

The code `executable.getReference().getOverriddingExecutable().getDeclaration().hasAnnotation(Function.class)` is the correct approach to get what you need. I do not think that it is good idea to support
`executable.getReference().getOverriddingExecutable().hasAnnotation(Function.class)`, because 
1) you need to know the spoon well to understand that you are not checking annotation of reference (which cannot have annotations)
2) we would have to implement all other methods and to offer them on references too - to be consistent

So yes, the correct code is little bit longer, but it is **clear** what you are doing. And it is very important aspect here in meta programming area, which is usually harder to understand by it's nature ;-)

Anyway there might be good idea to change the CtElement/CtRelation by a way the properties, which are not available on references are not inherited from CtElement.
@monperrus, please open new issue for that if you agree with that problem

**Comment by monperrus** [comment]
I agree, `getOverriddingExecutable().getDeclaration().hasAnnotation()` is the right approach.

In general, one should only call `getDeclaration()` (or even better `getTypeDeclaration()/getExecutableDeclaration()`) on references.

For historical reasons there are other many methods available in references, such has `hasAnnotation()`. 

However, I agree, there is a confusing bug here. 

To fix this, what I propose is to forbid using such a method on references


    CtReference#hasAnnotation() {
     throw new UnsupportedOperationException("cannot use hasAnnotation on a reference, consider using getTypeDeclaration() or getExecutableDeclaration() instead")
    } 

WDYT?

**Comment by Eric-W0** [comment]
Thank you for your answers.

I have no issue making the extra call to `getDeclaration()` to get `hasAnnotation()` right, but what happens if the overridden method is just in a third-party JAR? Wouldn't `getDeclaration()` return `null` in that case?

-Eric

**Comment by monperrus** [comment]
> what happens if the overridden method is just in a third-party JAR?

`getDeclaration` would return null, but `getExecutableDeclaration` would return a valid object (known as shadow method, built with runtime reflection)

**Comment by Eric-W0** [comment]
Ok thank you!

I'm ready to close the comment on my side if you want.

-Eric
