### ISSUE TITLE
Connect (IntelliJ) debugger with a breakpoint set in an annotation?

### ISSUE THREAD

**Issue by Eric-W0** [INRIA/spoon#1961]
Hey!

I'm not sure if such a thing exist but here's what I'd like to do:

1. Start IntelliJ debugger on a UnitTest
2. Within the test code, I'm calling Launcher#run
3. Within that run I'm going through a processor I defined (on the same project)
4. The execution path reaches a breakpoint
5. IntelliJ debugger takes over

Do you think this could be achieved?

**Comment by monperrus** [comment]
I think this is super fun and could be achieved (but probably not easily unless you're superman :-)

I know that @mduruisseau has done things on combining IDE and Spoon.

**Comment by Eric-W0** [comment]
Well I would fancy giving it a try.

@mduruisseau do you have any specific pointers I should look at? That would
most most helpful.

Diving into Google now... 😀

**Comment by mduruisseau** [comment]
Hello ! 

We have indeed developed a tool during my thesis that could help you. This tool uses Spoon to reverse-engineer Java code from an IntelliJ project in order to generate UML diagrams. These diagrams are interactive (a click on a class/attribute/method highlights the corresponding code in the IDE) and updated in real time.
However, we do not handle breakpoints nor unit test for the moment. We thought about adding extra information on diagrams to represent breakpoints or errors but this is not currently implemented.

You can visit the website we made for this tool : http://these.mickaelduruisseau.fr/VisUML/doc/index.html
In addition, this short video presents VisUML in a few minutes : https://www.youtube.com/watch?v=buyGojmbUpQ

Thanks for the mention @monperrus ! ;)

**Comment by monperrus** [comment]
leaving the issue open so that you can let us know about your progress.

**Comment by Eric-W0** [comment]
Update!

I finally got it working almost out of the box, with the added complication that I'm using Gradle in the middle:
- set the breakpoint on my processor
- launch Intellij unittest in debug mode, with unittest run being delegated to Gradle
- Gradle will build then launch the testrunner, passing the right arguments to the test process so that Intellij debugger will connect to it
- at some point, one of the tests will do a Launcher#run
- breakpoint is honored

Not sure why I got stumped in the first place (and therefore asked the question)...

**Comment by monperrus** [comment]
Thanks for the follow-up!
