### ISSUE TITLE
SpoonException when computing imports

### ISSUE THREAD

**Issue by mboussaa** [INRIA/spoon#2003]
Hi all,

I hit this exception when I run the following code. Any help? 

```
ImportScanner importContext = new ImportScannerImpl();
importContext.computeImports(classA);
```

`spoon.SpoonException: The lambda can be based on interface, which has only one method. But java.util.Comparator has at least two: compare(T,T) and equals(java.lang.Object)`

The concerned class is: [org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/result/method/annotation/RequestMappingHandlerMapping.java)

Thanks in advance.

Best,
Mohamed

**Comment by pvojtechovsky** [comment]
Hi Mohamed,

it is really interesting case. It looks like `Comparator#equals` is a special case of method which can be ignored in Spoon Lambda expression resolving algorithm, because that method is always implemented by java.lang.Object.

Could you create a pull request with a failing test? I can then fix it quite fast.

**Comment by filkra** [comment]
Hi Pavel,

I created a pull request over here https://github.com/INRIA/spoon/pull/2023. Let me know what you think.

Best Regards,
Filip
