### ISSUE TITLE
New branch convention

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#203]
Recently, we changed the versioning of spoon. The current release version is 4.0.0 and the snapshot version is 4.1.0-SNAPSHOT. But we have a third digit for hot fixes when we must apply a urgent modification. With our current management of the project, it is a little bit hard to apply hot fixes on Spoon so I would like to propose a new management of the project with an adaption of the git flow.

For example, see https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by pschichtel** [comment]
A big +1 from my side here, though not necessarily for Git-Flow

As this (rather important) issue is now open for over a month without any noticeable change, I'll give my 5 cents on the topic:

I think we (@boeserwolf91 and me) are trying to release our [Message Extractor project](/CubeEngine/messageextractor) since Spoon's 4.0 release with Java8 support (a requirement for other projects), but we were always getting test failures. The twist: The bugs were not actually the big problem. The bugs got fixed rather quickly and PR'ed, but a release containing them took weeks (see #207 and #222), until the next bigger update. This delayed further testing for us to the new release which caused the same situation all over again after the 4.1 release, when we discovered more blocking bugs.

Your release model should allow for bugfix releases in case of critical bugs. I follow quite a few open source projects on Github and they all have different approaches to solve a similar problem.

In my opinion Git-Flow is more designed for large development teams that manage multiple release and have SLA requirements for customers, so a structured and well-defined release process (which when done correctly can be automated entirely) is quite important. This usually goes hand in hand with tools like Stash (if you don't know it, think of it as a self-hosted github) that help enforce this workflow with features like branch protections and automated branch creation for issues. However for a small team like yours, this is simply overkill.

Here is one approach that I personally like and deploy in a simplified form for internal projects myself:
The Netty project maintains multiple stable release in parallel with independent release cycles. They develop on the master branch and cherry-pick applicable commits to the stable branches and publish releases on a regular basis or when critical issues got fixed (which in their context can mean security exploits). In addition to the stable release branches they create feature-branches and create PRs for bigger changes. This is a simple yet effective model that allows to develop new major changes while being able to easily backport bugfixes that also apply to older versions. It also doesn't create much overhead for developers for branching.
A benefit of this is also that people could create PRs that are targeted to an older version without interfering with the current development and these changes can even be ported forward to the master. 

This model can be reduced to 2 branches:

* master: the current development towards to next minor (_,X.0) or major (X.0.0) release
* stable: a branch that contains the code of the latest minor release + additional bug fixes that got backported from master

Feature branches can be used for large features or changes that touch a lot of code in order to keep the master somewhat stable and not conflict with normal development and community PRs.

No matter what you end up doing, at least do something so people don't have to **wait** weeks **for** a simple **bugfix**, because that **sucks**.

**Comment by pschichtel** [comment]
Additional note to the simple model i proposed: This could be extended with another branch called next which would be created before releases in order to build pre-release artifacts.

**Comment by monperrus** [comment]
I'm fine with bugfix releases in case of critical bugs. That's why we have introduced a third digit in the version number. If you need an urgent bugfix release on Maven, don't hesitate to tell us.

**Comment by boeserwolf91** [comment]
So why not use this third digit if you have it? :astonished: To my mind a bug fix release can be published containing bug fixes as long as they're compatible nearly automatically. Well and your branching system complicates the release cycle. Therefore @pschichtel suggests a "better" (better as long as you use it in a right way) system which helps contribution bug fixes to already published version(s). (just last version is okay I guess)

**Comment by GerardPaligot** [comment]
@monperrus With our actual branching system, we can't release a bugfix release on Maven Central only with bugfixes of the previous release. It is the reason why we should improved our branching system with a gitflow approach (or an alternative).

**Comment by monperrus** [comment]
> @monperrus <https://github.com/monperrus> With our actual branching
> system, we can't release a bugfix release on Maven Central only with
> bugfixes of the previous release.
Why?

**Comment by pschichtel** [comment]
@monperrus think about how you're currently doing releases. You're probably just running the maven release plugin on the master once you think it is right to publish a release. That works fine for major/minor releases.

No imagine the situation where in middle of the next development cycle a horrible bug is found that has to be fixed immediately, but the master has already received many new changes that are not yet tested or known to be unstable and not production ready.

So what would you do now?
With a the proposed branches you fix the bug, cherry-pick it into stable (or just directly fix it in stable, if it is not applicable to master anymore) and just run the maven release plugin there.

Currently you would need create a new branch locally based on the release tag created by the release plugin, apply the fixes run the release plugin (if that even works, as you probably don't want to push this). This 'works', but is not very transparent to the community and is not easily reproducible by peers. Maven is all about reproducible builds, but this situation does not easily allow this.

Now let's make the situation even worse: Another critical bug.
With the proposed branches: just do the same procedure again.

With the current setup: if you're lucky, you still have you local branch with the fix. If not you will have to apply all patches since the last minor release again.

With this setup its obvious nobody wants to make a bugfix release.

With specialized branches and a simple jenkins job bugfix releases can be as simple as clicking the merge button in a PR.

**Comment by pschichtel** [comment]
Any progress on this?

**Comment by GerardPaligot** [comment]
Unfortunately, everyone is in vacation. But, when they'll be returned, I'll talk about this issue with them!

**Comment by monperrus** [comment]
> This model can be reduced to 2 branches:
>
>    master: the current development towards to next minor (_,X.0) or major (X.0.0) release
>   stable: a branch that contains the code of the latest minor release + additional bug fixes that got backported from master

I like this. This is lightweight and 100% backward compatible with the current development model. It only requires some additional work at release time (maintaining "stable"). Is that right?

**Comment by pschichtel** [comment]
Exactly. For major Releases (Aka when you release the stuff from master), you simply run the release plugin as usual, switch into the stable branch and merge the tagged commit from master into stable. For minor Releases you could either directly work inside the stable branch and release it there, or branch from stable run release there, merge the tagged commit and remove the branch again. The point here is: the release plugin will create 2 commits (the release version and the next snapshot version), but the stable branch should only contain the first commit.

**Comment by GerardPaligot** [comment]
I want document this practice in the private documentation of Spoon (not shown in the website but available in the doc directory at the root of the project). @pschichtel @boeserwolf91 can you review it? :)

---

# Branch convention

## What is the meaning of each digit in the version X.Y.Z?

- X is the digit for the major version (major new features or major incompatible API changes).
- Y is the digit for the minor version (bug fixes or minor API changes).
- Z is the digit for the critical bug fixes of the current major or minor version.

## How to release a major or minor version?

- From the master branch, run the release plugin. The plugin will create one tag and 2 commits. 
- Switch to the stable branch and cherry pick the release version commit in the master branch.

## How to release a critical bug fix version?

- From the stable branch, run the release plugin. The plugin will create one tag and 2 commits. Make sure that you have upgraded the third digit!
- Switch to the master branch and pull all commits from stable to master.

**Comment by pschichtel** [comment]
The important part about the minor version (Y): API compatibility. So adding new APIs and changing implementations is fine, but the existing API should stay compatible. You can however deprecate APIs and schedule them for removal.

About the process:

After thinking a bit more about removing the second commit from the release plugin I wonder if it makes sense. With 2 branches it over-complicates the process. To properly do this you'd need a third branch (e.g. master, stable and released where released would only contain the released code and stable would kind of be a second master for changes to the last stable version).
I'd say for major/minor releases just run the release plugin inside master and merge master into stable, for bugfix releases just run it inside the stable branch.

In both processes I see a problem: When you have massive changes in master (imagine a major package refactoring) after a bugfix has been made and released inside stable, you can't easily merge master into stable on the next major/minor release. I think that's why Gitlab for example has a branch for every released minor version (..., 7-1-stable, 7-2-stable, ..., 8-0-stable). That way they don't have to merge master with stable again. The netty project does it similar. They have separate branches for API incompatible releases (3.x, 4.0, 4.1 and master for 5.0).

Maybe an option would be to just override stable with the new master, kind of dropping the bugfix releases in between releases. The history should in theory stay accessible through the tagged commit.

**Comment by GerardPaligot** [comment]
> Maybe an option would be to just override stable with the new master, kind of dropping the bugfix releases in between releases. The history should in theory stay accessible through the tagged commit.

This option seems odd. How you can override stable branch with the new master if the master branch is on the next release?

**Comment by monperrus** [comment]
> So adding new APIs and changing implementations is fine, but the
> existing API should stay compatible. You can however deprecate APIs
> and schedule them for removal.
Yes, this is what we do.

Best regards,

--Martin

**Comment by pschichtel** [comment]
Sorry for the late answer, I was quite busy.

> How you can override stable branch with the new master if the master branch is on the next release?

```bash
git checkout stable
git reset --hard master
git push --force origin stable
```

That's it

**Comment by GerardPaligot** [comment]
Yes, I know how you can update the stable branch but if you do that, the stable branch will be on the development version of spoon and not the last release.

**Comment by pschichtel** [comment]
well replace master with the tag from the release and that's it
