### ISSUE TITLE
refactor: fix all typos

### ISSUE THREAD

**Issue by zielint0** [INRIA/spoon#2126]
- https://github.com/INRIA/spoon/pull/2114 2018-06-26

**Comment by surli** [comment]
Hi @zielint0 

one good practice for us is to close an issue when it has been fixed. So please don't open issue for recerencing PRs that has already been merged. Thanks.

**Comment by zielint0** [comment]
@surli 
Hi Simon
But there are more typos to fix. The issue is not fixed.

What's wrong with referencing some PRs that fixes an issue?

Should I create one issue<=>one PR?

**Comment by surli** [comment]
> What's wrong with referencing some PRs that fixes an issue?

IMHO The issue should be here to help the community fixing a problem. Here opening a ticket for all small refactoring seems really overkill especially since you already opened the PRs and that don't need more explanations. 

We try to clean regularly our issues to avoid noise and to keep valuable information. I you think there is a need in refactoring Spoon regarding typos, checkstyle and so one: open a discussion about this topic and explain what you want to do and maybe how other people can help you. It will be more valuable than opening an issue for every kind of refactoring you're already doing.

**Comment by zielint0** [comment]
@surli 
Sounds sane. Thank you for explanation :)

**Comment by monperrus** [comment]
extracted the argument in #2133
