### ISSUE TITLE
Want suggestions for fixing of NPE SonarQube bugs in spoon

### ISSUE THREAD

**Issue by ashutosh1598** [INRIA/spoon#2250]
List of [NPE Sonarqube bugs](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&rules=squid%3AS2259&types=BUG) in spoon. When null dereferencing is of the type variable.functionCall(), we can simply add a not null check.

When in place of variable there is itslelf a function call which can return null, I don't know what repair to apply.  Adding try catch is not removing the SonarQube bug and is also not a good method to handle it. Suggest your thoughts so that I can configure the automatic [bot](https://github.com/kth-tcs/sonarqube-repair) to apply them.

**Comment by pvojtechovsky** [comment]
so you need to replace this code
```java
var.call1().call2()
```
by something null safe.  Right?

Just an idea ... may be wild ... What about something like this:
```java
callIfNotNull(var.call1(), r -> r.call2());
//with this  helper function
static <T, R> R callIfNotNull(T val, Supplier<R> invoke) {
if (val != null) {
  return invoke.get()
}
return null;
```
or you have to create local variable ... which will produce nicer stacktraces, but longer code ...

anyway you have to generate local variable name, which is not used yet.

**Comment by ashutosh1598** [comment]
Looks good. I will try to implement this with spoon.

**Comment by zielint0** [comment]
[*These aren't the droids you're looking for*](https://imgur.com/gallery/AUKUYOk)*

It's great to solve this problem but your are trying to remove a *result* instead of a *cause*.
The cause is using *null* to tell something about return value of the method.
For example in *extractVariable(String value)* if it is *not possible to extract a variable*, the *null* is returned:
[src/main/java/spoon/MavenLauncher.java](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&open=AWIvavnORIyoeYNsnfrw&resolved=false&rules=squid%3AS2259&types=BUG)
```
		private String extractVariable(String value) {
			if (value != null && value.startsWith("$")) {
				value = getProperty(value.substring(2, value.length() - 1));
			}
			return value;
		}
```
Now return value must be checked every time method is called.
Returning null is like playing with a grenade. Sooner or later the end is bad in both cases (explosion / NPE).

What are the problems with returning null and checking for it?
- missed check for null, also checking every time is laborious
- no clear information about the problem (why null was returned)
- it is thinking about low level construct (null) instead of high level (a class, like CtElement)

So the solution is not to return null & check for it!

What I would like to suggest is to avoid using null as much as possible including returning null from method.

Instead please refactor methods to use one of the null-free solutions:
- returning an empty String ""
- returning an empty collection (e.g. Collections.emptyList() / List.of())
- returning an Optional
- returning a *Null Object* (this is Null Object Pattern)
- throwing an exception (but only for exceptional cases)

The "drawback" of these solutions is that they requre more consideration and are more laborious to introduce. But they pay well in the long run (readability, maintainability, no NPEs).

Please take a look on:
- [Stop Returning Null in Java](https://www.codebyamir.com/blog/stop-returning-null-in-java)
- [Is returning null bad design?](https://stackoverflow.com/questions/1274792/is-returning-null-bad-design)

And what inventor of null wants to say us? (Tony Hoare, yes the same person that invented quicksort sorting algorithm!)
>“I call it my billion-dollar mistake. 
At that time, I was designing the first comprehensive type system for references in an object-oriented language. 
My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn’t resist the temptation to put in a null reference, simply because it was so easy to implement. 
This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years.”

And, for the God's sake, don't implement monstrosity that processes nulls and passes them further:
```
callIfNotNull(var.call1(), r -> r.call2());
//with this  helper function
static <T, R> R callIfNotNull(T val, Supplier<R> invoke) {
if (val != null) {
  return invoke.get()
}
return null;
```
Instead of solving the core of the problem, it makes it more complicated (sorry Pavel)! ;-)

*Not to be confused with the [*correct ones*](https://www.hollywoodreporter.com/heat-vision/spaceballs-at-30-bill-pullman-says-crew-worried-blue-screen-would-make-go-blind-1011687)!

**Comment by ashutosh1598** [comment]
Yes I think the information returned by SonarQube api is too little to implement these automatically.

**Comment by zielint0** [comment]
isSubTypeOf on TypeReference is not robust against missing declarations #2288

>The concrete problem is that CtTypeParameterreferenceImpl uses getTypeDeclaration() which in turn uses getDeclaration() which may return null.
The dereference to isSubtypeOf is then unchecked leading to the issue.

As you all see: returning null and then checking for it is a lost battle.

**Comment by pvojtechovsky** [comment]
So it looks like it is not good idea to try to fix NPE bugs automatically. The correct solution is refactoring of the code to not return null. So I am closing this issue. We can reopen it if needed of course ;-)
