### ISSUE TITLE
feature: add support for verbatim number literals

### ISSUE THREAD

**Issue by tempuser1909** [INRIA/spoon#2396]
Hi, can I ask how do I disable spoon's auto conversion of the numbers?

Example, when I write "short a = 0x10;", spoon will print out "short a = 16;" instead.

This affects the readability of the generated code as I want to view some numbers as hexadecimal at times.

Thank you.

**Comment by Egor18** [comment]
We can add the information about the original form to the `CtLiteral` and set it in the `JDTTreeBuilder`.
Then `DefaultJavaPrettyPrinter` could use that information to output the original form.

The question is in which form such information should be stored?
We can simply store `char[] source` from the `org.eclipse.jdt.internal.compiler.ast.Literal` in `CtLiteral`, but it would have a memory overhead (especially for large strings).
Another way is to store it is to create some enum with all kinds of literals in it and use it.
And finally we can hold that information only for numeric literals.

WDYT?

**Comment by pvojtechovsky** [comment]
You are on good way.

Do you have some link to a overview page, which shows, what kinds of literal representations exists in Java?
Or do you have an idea how many enum fields you would need to describe them all?
In your example above there would be enough to remember that it was hexadecimal representation of number.
But there are wild cases like https://docs.oracle.com/javase/8/docs/technotes/guides/language/underscores-literals.html
do we want to support that too?

> We can simply store char[] source from the org.eclipse.jdt.internal.compiler.ast.Literal in CtLiteral
that makes refactoring more complicated because you have two representations: 
* raw String
* parsed value
May be we might always store only raw string and to compute parsed value on the fly?
@monperrus WDYT?

**Comment by monperrus** [comment]
> May be we might always store only raw string and to compute parsed value on the fly?

yes, we don't want to maintain two representations in sync, this is super error prone.

**Comment by tempuser1909** [comment]
@pvojtechovsky, I think this feature should only affect numeric literals.

Here is a link that discusses about that.
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

**Comment by pvojtechovsky** [comment]
```java
interface FormattedLiteral<T> {
T getValue();
void setValue(T value);
String print();
... other methods might depend on the sub classes/interfaces ... like FormattedNumber#setMode(dec/hex/bin) ...
}
```
then `CtLiteralImpl#value` might contain either literal value directly (like now) or `FormattedLiteral` if special formatting is needed.

WDYT?

**Comment by Egor18** [comment]
>CtLiteralImpl#value might contain either literal value directly (like now) or FormattedLiteral

I'm afraid that it will break a lot of old code because instead of getting let's say `Integer` from `getValue()`, users would get `FormattedLiteral`. I think we should not break the current `getValue()`.

In addition, right now I'm not sure that we should store the **exact** representation of the literal, because we could end up by storing the exact representation of all elements at all.
If the user wants to have it, he probably should create (derive) a new pretty-printer, which would print literals directly from the actual source file, using their `SourcePoisition`. 

However, it may be useful to have information about the representation of the Integer or Floating point literals. Something like this:
`enum Base { DECIMAL, HEXADECIMAL, OCTAL, BINARY };`
And for other literals, the representation value could be `NONE` or `null`.

> An integer literal may be expressed in decimal (base 10), hexadecimal (base 16), octal (base 8), or binary (base 2).
> A floating-point literal may be expressed in decimal (base 10) or hexadecimal (base 16).

https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.10

What are your thoughts?

**Comment by monperrus** [comment]
> I think we should not break the current `getValue()`.

Fully agree. Spoon always tries to remain fully backward compatible.

> `enum Base { DECIMAL, HEXADECIMAL, OCTAL, BINARY };`

good idea.

What about a new method in CtLiteral, such as `toOriginalString()`?

**Comment by Egor18** [comment]
> What about a new method in CtLiteral, such as toOriginalString()?

Do you want it to read the original string from the file, using Source Position?

**Comment by monperrus** [comment]
That's an option which seems OK to me.

**Comment by Egor18** [comment]
In my opinion `toOriginalString()` will be extremely inefficient, because it will be required to open read and close the whole file for each invocation. If a user wants exact representations of CtElements (not only CtLiterals) he should probably load the source file in memory and use it from there.
We could probably provide this functionality in spoon, but that's a different story.

So for this task I suggest to simply add information about the base to the numeric CtLiterals and make Pretty Printer use them. (I provided the PR).
