### ISSUE TITLE
Visualization: Video of the evolution of Spoon 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#2877]
https://www.youtube.com/watch?v=AlWAR5wuyMg

Made with Gource.

Thanks @cesarsotovalero!

**Comment by tdurieux** [comment]
@cesarsotovalero Nice, does spoon have the same evolution than other open-source projects?

**Comment by msteinbeck** [comment]
Our research group focuses on the visualization of large software systems. In the attachments you will find a zip archive containing a html file that uses D3 to visualize Spoon's inter-file dependencies. By the way, we use Spoon to calculate dependencies :). Due to the number of files, the visualization is rendered in 4K. You may use the mouse wheel to zoom in or out. You may further configure the bundling strength using the keys 0--9 (percentage) or `w` and `s`.

[spoon.html.zip](https://github.com/INRIA/spoon/files/2855347/spoon.html.zip)

**Comment by monperrus** [comment]
cool, thanks for sharing! hosted at http://spoon.gforge.inria.fr/visu/spoon.html

how to read it?

**Comment by msteinbeck** [comment]
This visualization technique is called hierarchical edge bundling. It has been developed to enhance the visualization of graphs with lots of edges. In this example, all java files of Spoon are arranged on a circle. Whenever there is a dependency between two files `a` and `b`, an edge is drawn from `a` to `b`. All edges follow the hierarchy of the system, that is, the package hierarchy.

You can hover a file with your mouse to see the actual type of the dependencies. A red edge means "imports", a green edge means "is imported by". For example, CtElement is imported by lots of other files, as depicted by the several green edges. Use `ctrl + f` to search for a specific file.

**Comment by monperrus** [comment]
So beautiful that I made a screenshot: https://github.com/INRIA/spoon/issues/2878
