### ISSUE TITLE
feat: UnresolvedBug annotation

### ISSUE THREAD

**Issue by nharrand** [INRIA/spoon#3001]
The most useful sort of bug report is actually a pull request with a failing test case. We do have quite a lote of those, and that's great.
But, today we cannot merge them as they would break CI. 
What we could do (thanks @oscarlvp ) is having an annotation for test case `@UnresolvedBug`. We would not run these test in CI, but a regular `mvn test` would run them.

WDYT?

**Comment by monperrus** [comment]
It's a nice idea. And we would check that there exists an issue:
1) referring to this test
2) that is still open
3) that is labeled "bug"

**Comment by oscarlvp** [comment]
Tests may have a category in JUnit and Surefire can exclude or include tests based on these categories. Check the following links:
https://stackoverflow.com/questions/14132174/how-to-exclude-all-junit4-tests-with-a-given-category-using-maven-surefire
https://www.mkyong.com/unittest/junit-categories-test/
https://junit.org/junit4/javadoc/4.12/org/junit/experimental/categories/Categories.html
So instead of a custom annotation, you may have an `UnresolvedBug` category, excluded by default in the `pom.xml` configuration.
But a custom annotation could be used in combination with the category, to link the test to the Github issue and having some sort of integration that could check that when the issue is solved, the test should not have the `UnresolvedBug` category and vice versa.

You could have something like this:
```Java
@Test
@Category(UnresolvedBug.class)
@GithubIssue(3000)
public void testForNastyBug() {
}
```
