### ISSUE TITLE
community: activate probot-stale 

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3177]
Hi all, what about activating probot-stale on Spoon?

https://probot.github.io/apps/stale/
Close stale Issues and Pull Requests on Spoon

**Comment by surli** [comment]
I'm really not in favor of having it for the issues: we have lot of closed issues (almost 1K) and some old issues that are still opened because we did not get the time to do them, or they are part of a bigger roadmap.

IMO it's good to keep them open: as soon as we close them, it will become really difficult to find them back.
Now, no doubt that we might want to do some cleaning in those open issues. 

Now regarding PR it's another subject since our codebase is moving quickly so old PR are far more difficult to merge afterwards. So I'd be ok to have it for PRs.

**Comment by slarse** [comment]
Revisiting this topic.

The amount of issues are steadily increasing here, and there are ~17-18 stale pull requests.

I think automatically closing both issues and pull requests is a good idea. The contributing guidelines say that issues and PRs that haven't seen activity in 3 months are closed automatically, but this is not actually enforced.

**For pull requests**, I suggest that Probot notifies after 3 months of inactivity and closes after an additional 7 days.

For issues, I suggest that we have Probot post a comment that the issue is stale and will be closed within X days (perhaps 14?) if no further activity is seen. Maintainers watching the repo will be notified of Probot's comment, and can then check the issue. If it should be kept open, we simply remove the stale label and add an exempt label (perhaps `pinned` or `probot-ignore` or something like that). Otherwise, we let Probot do its thing.

I think it's much better for a bot to close issues and pull requests automatically, rather than have a maintainer do it, for two reasons. First, it puts the responsibility of keeping track of stale issues on the bot, which is pretty huge. Second, it's less likely that the issue/PR author takes any kind of offense to a _bot_ closing their issue/PR, than a maintainer doing it. The former is just "the way it is", while the latter can be taken personally.

Thoughts?

**Comment by monperrus** [comment]
duplicate of https://github.com/INRIA/spoon/issues/2556, closing
