### ISSUE TITLE
LiteralHelper replaces printable Unicode characters with escape sequence

### ISSUE THREAD

**Issue by Banbury** [INRIA/spoon#3203]
My code contains a lot of text containing German Umlaute. When I pretty print this text, all the Umlaute are replaced by unicode escape sequences. That makes the text unreadable.
Since my code is UTF-8 no escaping is necessary. But I can't turn off this 'feature'.
I would prefer a way to tell the pretty printer, which characters I want escaped and which not.
Also, for some reason the single quote character (') is escaped, too.

**Comment by nharrand** [comment]
Thanks for the report!

I guess we should give an option to adapt to the encoding of the output file for `LiteralHelper#appendCharLiteral(StringBuilder, Character, boolean)` ( https://github.com/INRIA/spoon/blob/99775fcf4e51ef73c80e2ef04edd6131615885e2/src/main/java/spoon/reflect/visitor/LiteralHelper.java#L108 ).

**Comment by Banbury** [comment]
It would make sense, since there is an option to set the encoding already.

**Comment by monperrus** [comment]
For inspiration see #3014.

**Comment by Egor18** [comment]
I tried to reproduce the issue and it looks like Spoon handles German Umlaut properly (UTF-8).
However, it starts escaping it (as well as the single quote character) when special character is found in the string.
Special character essentially means that the string in the source is not the same as the string in the literal.
Here is an example:

Input:

```
public class EscapedLiteral 
{
    String s1 = "Köln";

    String s2 = "'Köln'";

    String s3 = "Köln\u0001";

    String s4 = "'Köln'\u0001";
}

```
Spoon output:

```
public class EscapedLiteral 
{
    String s1 = "Köln";

    String s2 = "'Köln'";

    String s3 = "K\u00f6ln\u0001";

    String s4 = "\'K\u00f6ln\'\u0001";
}
```

Could you please provide the source file you are trying to process (or some minimal example)?
Because it looks to me that your strings probably contain some other special characters.

**Comment by Banbury** [comment]
The only other special characters, that I'm aware of, are some single quotes ('), that got escaped unnecessarily, too.

**Comment by Egor18** [comment]
Could you please attach your file? So I can reproduce your case.

**Comment by Banbury** [comment]
I'll try to create a reproducible example. But it will take a day or two.

**Comment by Egor18** [comment]
Thanks

**Comment by Banbury** [comment]
Here's a minimal example of what I'm trying to do.

```
package de.muenchen.iteraplanplausis.utils;

import spoon.Launcher;
import spoon.processing.AbstractProcessor;
import spoon.reflect.CtModel;
import spoon.reflect.code.CtBinaryOperator;
import spoon.reflect.code.CtCodeElement;
import spoon.reflect.code.CtLiteral;
import spoon.support.compiler.VirtualFile;

public class SpoonUnicodeBug {
	public void run() {
		Launcher l = new Launcher();
		l.addInputResource(new VirtualFile("class A { void m() { System.out.println(\"Hellö \" + \"Wörld!\");} }"));
		l.buildModel();
		l.addProcessor(new StringConcatProcessor());
		l.process();
		CtModel m = l.getModel();
		System.out.println(m.getRootPackage().getType("A").toString());
	}

	public static void main(String[] args) {
		new SpoonUnicodeBug().run();
	}

	private class StringConcatProcessor extends AbstractProcessor<CtLiteral<?>> {
		@Override
		public boolean isToBeProcessed(CtLiteral<?> candidate) {
			return candidate.getType().isSubtypeOf(getFactory().Type().STRING) &&
					candidate.getParent() instanceof CtBinaryOperator;
		}

		@Override
		public void process(CtLiteral<?> element) {
			CtCodeElement s = ((CtBinaryOperator<?>) element.getParent()).partiallyEvaluate();
			element.getParent().replace(s);
		}
	}
}
```

Output:
```
class A {
    void m() {
        java.lang.System.out.println("Hell\u00f6 W\u00f6rld!");
    }
}
```

As you can see, there are no other special characters in the string.

**Comment by Banbury** [comment]
I've just found out, that after calling `partiallyEvaluate` the `CtCodeElement s` has no type. Casting `s` to CtLiteral<String> and then adding a type, will produce a string without escaped characters.

**Comment by Egor18** [comment]
OK, I figured out that the reason for such behavior is that partial evaluator creates a new literal from concatenation and this literal has no source position (which makes sense since there is indeed no such element in the code):
https://github.com/INRIA/spoon/blob/5e23a7e1b2353ff9abab1e3e4e37268e03cd9af9/src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java#L120
But LiteralHelper uses source position to determine whether to escape characters in a string or not:
https://github.com/INRIA/spoon/blob/341c2428b0735a5cb2912513b79485982f9bfc81/src/main/java/spoon/reflect/visitor/LiteralHelper.java#L73-L81
So no source position => mayContainsSpecialCharacter => escape umlaut and other stuff.

I'm not sure, but I guess we can escape only ISOControl characters. I'll create the PR. WDYT?
