### ISSUE TITLE
Target type of a static field must be a CtTypeAccess

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#346]
see test TargetedExpressionTest::testStaticTargets
in https://github.com/monperrus/spoon/tree/target

**Comment by GerardPaligot** [comment]
Here, the problem is: What should returned `getTarget()` on a `CtFieldAccess`?

According to the [documentation of this method](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/code/CtTargetedExpression.java#L36) declared in the `CtTargetedExpression` interface, we should returned `null` but there is one particular case: when we specify `this.` in front of the field access. It isn't a good practice but it is valid.

We can remove this information when we are in a static context but there is a consequence with this modification: we can't reprint "this" in `DefaultJavaPrettyPrinter`. For me, this case is the only case where `getTarget()` shouldn't returned `null` but `ThisAccess` and must be specified in the javadoc.

@monperrus your opinion?

**Comment by monperrus** [comment]
the only thing is that elements.get(0/1/2) should return the same value for sake of consistency.
 
I'd say null is a good option

**Comment by GerardPaligot** [comment]
I don't agree with you. Like you got a different target for a field not static (`this.field` and `field`). Static fields shouldn't be different.

**Comment by monperrus** [comment]
The point is that they should all return the same object because they
refer to the same thing.

It's related to the way we refer to classes, so it's also related to #349.

I've looked at the code and this point is a mess, to refer to a class we
have either:
CtFieldAccess on .class
and
CtLiteral containing a TypeReference (rather a hack, used for instanceof
and annotation values)

One option is to introduce a clean CtClassReferenceExpression (similar
to CtExecutableReferenceExpression) and to unify this.

**Comment by GerardPaligot** [comment]
Here, the target type must be a `CtTypeReference` when we use a static field.
