### ISSUE TITLE
Can't get to method declaration from a CtInvocation object with Maven

### ISSUE THREAD

**Issue by andrewbwogi** [INRIA/spoon#3667]
In a Maven project with the three classes below in the source folder, run `mvn exec:java -Dexec.mainClass="Main"` in the project root folder. With this setup the parsed invocation returns an executable reference that returns null instead of a method declaration. However, remove the inner class parameter and argument from the Invocation class and the executable reference will return the declaration when run with the same Maven command. This problem does not occur when running the program with the java command, a method declaration is returned in both cases.  

```java
public class Main {

    public static void main(final String args[]) {
        Launcher launcher = new Launcher();
        launcher.addInputResource("./src/main/java/Invocation.java");
        launcher.buildModel();
        CtModel model = launcher.getModel();
        CtPackage root = model.getRootPackage();
        CtType t = root.getType("Invocation");
        CtMethod invMethod = t.getMethod("invocation");
        CtInvocation inv = (CtInvocation) invMethod.getBody().getStatements().get(0);
        System.out.println(inv.getExecutable().getDeclaration());
    }
}
```

```java
public class Invocation {

    public void invocation(){
        method(new Test().new Inner());
    }

    public void method(Test.Inner x){
    }
}
```

```java
public class Test {

    public class Inner {
        int method(){
            return 2;
        }
    }
}
```
Manjaro 20.1
Maven 3.6.3
Java 11
Spoon 8.2

**Comment by slarse** [comment]
@andrewbwogi I believe that the problem here is that when you run with the Maven exec command, the `src/main/java/` directory is not added to the classpath. As only the `Invocation.java` file is explicitly added as a resource to Spoon, this might result in Spoon not having access to the `Test` class. It gets really dicy in Spoon to build the AST when there is only partial type information available. Probably, there is some difference when you run in the other mode such that the `Test` class actually ends up on the classpath.

Try adding the entire directory as a resource instead:

```diff
-launcher.addInputResource("./src/main/java/Invocation.java");
+launcher.addInputResource("./src/main/java/");
```

Does that solve the issue? If so, then I don't think the issue you report is a bug. Spoon just doesn't have access to the declaration.

**Comment by andrewbwogi** [comment]
Adding the entire directory as resource solves the problem, thanks @slarse

**Comment by slarse** [comment]
@andrewbwogi Great, so that's definitely the cause then! I'm still a bit perplexed that you actually got something non-null when you decreased the complexity of the method call. The docs clearly state that the return value is null if the declaration is not available: https://github.com/INRIA/spoon/blob/81cd93b78977c1e79bef63956fc86f06c923f8fa/src/main/java/spoon/reflect/reference/CtReference.java#L44-L51

I'll look into why that happened if I've some time to spare.

**Comment by andrewbwogi** [comment]
@slarse, it seems reasonable that non null is returned with the simplified invocation since it only refers to elements in `Invocation` which is always added as resource.

**Comment by slarse** [comment]
@andrewbwogi Ah, right, that makes sense. Good catch :)
