### ISSUE TITLE
processor cannot be used if they contain fields with default expressions

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#369]
error:
error: Unable to instantiate processor "bcu.nopol.processor.LsClass" - Your processor should have a constructor with no arguments

seems that processors cannot have constructors as well

**Comment by GerardPaligot** [comment]
This error occurs when you call `addProcessor(Class)` ([code](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/QueueProcessingManager.java#L62)). You need to have an empty constructor when you create a new instance from `Class.newInstance()`.

I don't see the bug here. You can call `addProcessor(Processor<?>)` if you want create a processor with parameters in the constructor.

**Comment by GerardPaligot** [comment]
With this constructor:

```java
public class NoConstructorProcessor extends AbstractProcessor<CtClass> {
	CtBlock bWithBref;
	CtBlock bWithBlock;

	@Override
	public void process(CtClass element) {
		
	}
}
```

I can't reproduce your bug. Below the test case:

```java
@Test
public void testNoConstructorProcessor() throws Exception {
	final Launcher launcher = new Launcher();
	launcher.addInputResource("./src/test/java/spoon/test/processing/processors");
	launcher.setSourceOutputDirectory("./target/trash");
	launcher.addProcessor("spoon.test.processing.processors.NoConstructorProcessor");
	launcher.process();
}
```

**Comment by monperrus** [comment]
Those fields have no default expression.

if you try with

    CtBlock bWithBref = new CtBlockImpl();

?

--Martin

**Comment by GerardPaligot** [comment]
The same with:

```java
public class NoConstructorProcessor extends AbstractProcessor<CtClass> {
	CtBlock bWithBref = new CtBlockImpl<>();
	CtBlock bWithBlock = new CtBlockImpl<>();

	@Override
	public void process(CtClass element) {

	}
}
```

**Comment by monperrus** [comment]
Then we can close this issue
