### ISSUE TITLE
Question: How to get method implementations

### ISSUE THREAD

**Issue by hardikSinghBehl** [INRIA/spoon#3721]
```
CtType s = new TypeFactory().get(String.class);
CtClass a = Launcher.parseClass(s.toString());
System.out.println(a.toString());
```
How can i get the implementation code of the methods in String class
im only getting methods in the format
```
public java.lang.String concat(java.lang.String arg0) {
 }
```
thank you.

**Comment by nharrand** [comment]
Hi @hardikSinghBehl ,
You are encountering this behavior because you probably don't have sources for the class `String`. Hence the CtClas you're getting is a shadow class. (You can test it by calling the method `#isShadow`).

If you actually need to access the body of this method you have two options: (i) find the sources, (ii) use one of the [spoon decompiler](https://github.com/INRIA/spoon/tree/master/spoon-decompiler) directly on the bytecode.
