### ISSUE TITLE
update website publication job

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#3759]
Until today our website http://spoon.gforge.inria.fr was hosted on the [INRIA GForge](https://gforge.inria.fr/). Yes, this service will be discontinued, see https://intranet.inria.fr/Actualite/Report-a-l-ete-2021-et-plan-d-action-Arret-de-la-forge

As alternative solution, @seintur and myself have worked to move it to Github.io.

Now, the HTML pages are hosted on https://github.com/SpoonLabs/SpoonLabs.github.io/

Yet, we need to update the cron task for publishing the website, which is a Jenkins job:

* Job: https://ci.inria.fr/sos/job/Website%20Deployer/
* Source :https://github.com/SpoonLabs/spoon-ci-config/blob/master/jenkins/jobs/Website%20Deployer.xml

**Comment by monperrus** [comment]
The job must handle both the Jekyll site in `docs` and the Javadoc, see #3762

**Comment by slarse** [comment]
I'm doing some infrastructure work at the moment so I'll pick up this one, too.

**Comment by slarse** [comment]
It took me a while to familiarize myself with Jenkins, but now I've got it all mostly figured out. I've adapted the current deployment script to generate the new site, but I haven't written the deployment part yet.

@monperrus Should we deploy automatically to SpoonLabs/spoonlabs.github.io, or should we open pull requests whenever the website changes?

Also, I can't find that the Javadocs for previous (stable) versions are hosted anywhere, are they? Should we to set it up such that we host the docs for, let's say, every stable release from Spoon 8 and up? Plus snapshots?

**Comment by monperrus** [comment]
that's great.

> @monperrus Should we deploy automatically to SpoonLabs/spoonlabs.github.io

yes!

**Comment by slarse** [comment]
@monperrus I've got everything working now in a simple GitHub Action workflow (simpler than Jenkins as we have the credentials at hand). Here's an [automatic update example on my own fork](https://github.com/slarse/SpoonLabs.github.io/commit/810b4c12c16b4bf7ea0c6a6e1e14848b59c23854). Note that the diff is quite large due to the switch in markdown processor (see #3859).

As the move from Travis to GHA was kind of painful, I've written the deployment script to be relatively agnostic of where it is executed. In case we need to move again. For the final revision, I'll configure the action **to update the website once a day**.

Before I can make the final preparations for this to work on the actual Spoon website, I need #3859, #3862 and #3863 to be merged.

**Comment by monperrus** [comment]
Thanks for the progress.

> I need #3859, #3862 and #3863 to be merged.

Done

**Comment by slarse** [comment]
FYI the new automation is ready for merge over at SpoonLabs/SpoonLabs.github.io#2

**Comment by monperrus** [comment]
Closing then!

**Comment by monperrus** [comment]
@slarse what about deleting the Jenkins job https://ci.inria.fr/sos/job/Website%20Deployer/?

**Comment by slarse** [comment]
@monperrus Yep, I think we're comfortable enough with the GHA one now that the old deployer is just baggage. Will delete tomorrow morning.

**Comment by slarse** [comment]
Job deleted.

**Comment by monperrus** [comment]
Thanks.
