### ISSUE TITLE
Question: performance of pretty print

### ISSUE THREAD

**Issue by danglotb** [INRIA/spoon#3778]
Hello,

I have a question about potential misusages of pretty print in Spoon, that lead to bad performance. Basically, I'm cloning a test class, I rename it and I duplicate a particular test method.

If I do 10 or 100 duplications, the printing is ok. However, If I go for 1k or more, it takes a lot of time to print.

Here, the snippet of code that I use to print:

```java
private void printCtType(CtType<?> type) {
        final File directory = new File(this.rootPathFolder + "/" + TEST_FOLDER_PATH);
        type.getFactory().getEnvironment().setSourceOutputDirectory(directory);
        final PrettyPrinter prettyPrinter = type.getFactory().getEnvironment().createPrettyPrinter();
        final String fileName = this.rootPathFolder + "/" +
                TEST_FOLDER_PATH + "/" +
                type.getQualifiedName().replaceAll("\\.", "/") + ".java";
        LOGGER.info("Printing {} to {}", type.getQualifiedName(), fileName);
        try (final FileWriter write = new FileWriter(fileName)) {
            write.write(prettyPrinter.printTypes(type));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

This is my (simplified) processing:

```java
@Override
    public void process(CtMethod<?> ctMethod) {
        System.out.println("Processing " + ctMethod.getDeclaringType().getQualifiedName() + "#" + ctMethod.getSimpleName());
        final CtType<?> originalTestClass = ctMethod.getParent(CtType.class);
        final CtMethod<?> clone = ctMethod.clone();
        final CtType<?> testClass = originalTestClass.clone();
        originalTestClass.getPackage().addType(testClass);
        testClass.setSimpleName(testClass.getSimpleName() + "_" + ctMethod.getSimpleName() + "_" + this.nbDuplication);
        // replace all references of originalTestClass by references of testClass
        // duplicate test method clone in testClass
    }
```

Should I do something differently? Should I print the classes differently?

Thank you very much!

**Comment by slarse** [comment]
Hi!

I don't see anything overtly wrong about your printing code, printing types with `PrettyPrinter::printTypes()` shouldn't impose any particular overhead.

If your `process` method executes 1k times, then you'll have 1k new classes in the package. That's kind of a lot, and may simply take a long time to print. You could try timing the actual call to `prettyPrinter.printTypes(type)` and see if the time to execute it increases with increasing amount of duplications. If that's the case, something's not right, because unless your `process` method executes on the cloned classes (which would mean they increase in size as methods are added), there's no reason for print time for the individual classes to increase.

**Comment by danglotb** [comment]
Hello, 

Thank you very much for your answer.

I did a little experiment a printed the time that takes Spoon to print the test classes, thus the number of duplications.

10 duplications
```txt
[INFO] Processing Done...
[INFO] Printed com.google.gson.functional.CustomTypeAdaptersTest_testCustomNestedSerializers in 236 ms (10 duplications)
[INFO] Printed com.google.gson.functional.StringTest_testJavascriptKeywordsInStringSerialization in 9 ms (10 duplications)
```

2001 duplications
```txt
[INFO] Processing Done...
[INFO] Printed com.google.gson.functional.CustomTypeAdaptersTest_testCustomNestedSerializers in 29889 ms (2001 duplications)
[INFO] Printed com.google.gson.functional.StringTest_testJavascriptKeywordsInStringSerialization in 426 ms (2001 duplications)
````

It looks like that there is not only the number of duplications but also the test method duplicated itself.

`testCustomNestedSerializers`(2k duplication, 30s to print):
```java
public void testCustomNestedSerializers() {
    Gson gson = new GsonBuilder().registerTypeAdapter(
        BagOfPrimitives.class, new JsonSerializer<BagOfPrimitives>() {
      public JsonElement serialize(BagOfPrimitives src, Type typeOfSrc,
          JsonSerializationContext context) {
        return new JsonPrimitive(6);
      }
    }).create();
    ClassWithCustomTypeConverter target = new ClassWithCustomTypeConverter();
    assertEquals("{\"bag\":6,\"value\":10}", gson.toJson(target));
  }
```

`testJavascriptKeywordsInStringSerialization`(2k duplications, 0.5s to print):
```java
public void testJavascriptKeywordsInStringSerialization() {
    String value = "null true false function";
    String json = gson.toJson(value);
    assertEquals("\"" + value + "\"", json);
}
```

WDYT?

**Comment by slarse** [comment]
Hi again,

First I just want to make sure that I understand what's going on. You take a test class T, duplicate a method M in it, insert the class into the original package and rename the class. You do that x amount of times. So, after running, you have x copies of T in the package, each with one method more than the original T. Is this correct? If this is the case, then printing any one of those copies should be about as fast as printing T, and printing x copies should take about x times longer (this is not an exact science, but the running time increase should be linear).

As for the running times that you show, is that for printing _one_ class, or _all_ duplicated classes? If it's the latter, then the running time increase seems rather linear, as there are 200 times as many duplications and the running time is ~127 and ~47 times larger. If it's printing _one_ type, then something is off here, or I've misunderstood the details of what you're doing.

> It looks like that there is not only the number of duplications but also the test method duplicated itself.

If the method is large, then yes. Otherwise, it's probably more about the class that's duplicated. As outlined above, if I don't misunderstand what you're doing, you get a whole lot of copied test classes.

**Comment by danglotb** [comment]
> First I just want to make sure that I understand what's going on. You take a test class T, duplicate a method M in it, insert the class into the original package and rename the class. You do that x amount of times. So, after running, you have x copies of T in the package, each with one method more than the original T. Is this correct?

Yes, but no. The method M is duplicated `x` times inside the same test class. For example, I take the test class `com.google.gson.functional.CustomTypeAdaptersTest`, and then I duplicate 2000 time the test method `testCustomNestedSerializers`, (add to the name of each duplication a suffix like `_x` where is is the index of the duplication:
`testCustomNestedSerializers_0`, `testCustomNestedSerializers_1`, ..., `testCustomNestedSerializers_x`). So in the end, I have `com.google.gson.functional.CustomTypeAdaptersTest_testCustomNestedSerializers`, which is a copy of the original test class that contains `x` duplication of `testCustomNestedSerializers`.

> As for the running times that you show, is that for printing one class

I showed the running times for printing four test classes:
1. `com.google.gson.functional.CustomTypeAdaptersTest` with **10** duplications of `testCustomNestedSerializers` (236 ms)
2. `com.google.gson.functional.StringTest` with **10** duplications of `testJavascriptKeywordsInStringSerialization` (9 ms)
3. `com.google.gson.functional.CustomTypeAdaptersTest` with **2001** duplications of `testCustomNestedSerializers` (29889 ms)
4. `com.google.gson.functional.StringTest` with **2001** duplications of `testJavascriptKeywordsInStringSerialization` (426 ms)

Is it clearer? Thank you very much! :smiley:

**Comment by slarse** [comment]
Right, then I get it. It was this part:

```java
        final CtType<?> testClass = originalTestClass.clone();
        originalTestClass.getPackage().addType(testClass);
        testClass.setSimpleName(testClass.getSimpleName() + "_" + ctMethod.getSimpleName() + "_" + this.nbDuplication);
```

That made me think that each test class was duplicated, because you first clone the class, then add the clone to the package, and then _rename_ the class, so I thought you'd end up with a ton of test classes with different names.

But okay then, that running time increase still seems rather reasonable. Consider that `CustomTypeAdaptersTest` is around 500 lines of code, and `testCustomNestedSerializers` is 11 lines long. If you add 10 copies of that, you get ~600 lines of code. That's our baseline, 236 ms to print 600 LOC.

Now, add 2000 copies. That will yield around `500 + (11 * 2000) = 22600` LOC. That's around 38 times as many LOC as the baseline, and it takes `29889 / 236 = 126` times longer to print. While not a perfectly linear increase in terms of LOC, it's pretty close. We'd probably get closer to linear by looking at the amount of nodes in the AST instead of amount of lines in the output, as each node is pretty-printed. And then, some nodes take longer to print than others, etc etc.

For `StringTest`, the story is pretty much the same. The file is roughly 140 LOC, and `testJavascriptKeywordsInStringSerialization` is 5 LOC. Baseline is 9 ms to print 150 LOC, and compare 426 ms to print 10150 LOC. That's a `426 / 9 = 47` times running time increase for a `10150 / 150 ~ 68` times LOC increase. So, it seems to add up.

Comparatively, `testCustomNestedSerializers` is pretty complex, each line having many nodes, whereas `testJavascriptKeywordsInStringSerialization` is very simple with just a few nodes per line. This would explain the differences in scaling.

Now, I'm not saying this is _good_ performance, the pretty-printer could surely be optimized, but it still seems like rather linear increases in running times. What do you think?

**Comment by danglotb** [comment]
I'm convinced by your demonstration. Thank you very much! 

I'm gonna try to hack this by not using Spoon to print but rather print one by one the test method using Java API and `CtMethod#toString()`.

Thank you for your answers, this is great! :smile:

**Comment by slarse** [comment]
You're welcome!
