### ISSUE TITLE
Cache Maven dependencies to speed up build process

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#3840]
We spend almost 4 minutes just downloading dependencies in each build (about 1/3 of total build time). That's made worse by us disabling connection pooling to avoid transfer timeouts.

Caching the .m2 directory could significantly speed up the builds.

**Comment by MartinWitt** [comment]
Isn`t caching dependencies risky if we have stale or old ones? Assuming we update in a PR a dependency and use the new API.
I personally had a lot of problems with mavens version resolution in plugins if we don't specify every version number(which we should).
Have you tested your caching mechanism, because debugging caching problems in the CI is the most antifun thing I ever had?
But improving the CI time is always a good improvement. Do you have a specific caching solution in mind or has maven some included?

**Comment by slarse** [comment]
Haven't tested it yet, but I'm gonna try out https://github.com/actions/cache

Plan is to find a way to evict the cache by time (e.g. every day). That should give massive speedup at minimal risk of having stale dependencies.

If I can't evict the cache based on time, then I'd say it's too risky.
