### ISSUE TITLE
Infinite loop in buildModel

### ISSUE THREAD

**Issue by gchaperon** [INRIA/spoon#3903]
Hi!
I am trying to process a file but the library gets stuck when trying to build the model.
The file that I am trying to process is [this one](https://pastebin.com/dmkqHTbN)

The code I am using is below:
```java
import spoon.FluentLauncher;
import spoon.reflect.CtModel;

public class TestBuildModelStuck {
	public static void main(String[] args) {
		String path = "/path/to/myfile.java";
		CtModel model = new FluentLauncher().inputResource(path).buildModel();

	}
}
```

Using the debugger I managed to see that buildModel is stuck in an infinite loop here:
https://github.com/INRIA/spoon/blob/fecec810886819c09ffc4955faeb4f50f64e07a3/src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java#L513
`off` never goes below zero

The part of my file it gets stuck on is `T.Entry<K, V>`, found in line 508 of my file.

I am failing to see why this is happening. Is that syntax not allowed or invalid?

**Comment by slarse** [comment]
Hi @gchaperon,

That's perfectly valid Java. I haven't seen it written like that before, but `T.Entry<K, V>` erases just fine to `Map.Entry`, so there's no type problem.

I can also reproduce the bug. The problem is that JDT resolves `T` as a qualified type reference, but Spoon does not appear to handle the case where that's a type parameter reference. In other words, this is a bug!

**Comment by slarse** [comment]
Here's a minimal piece of code that reproduces the bug:

```java
Launcher.parseClass("public class Main<T extends java.util.Map<String, String>> { T.Entry<String, String> entry; }");
```
