### ISSUE TITLE
CtMethod.getOriginalSourceFragment().getSourceCode(); contains comments even with launcher_test.getEnvironment().setCommentEnabled(false);

### ISSUE THREAD

**Issue by djaekim** [INRIA/spoon#4044]
I am trying to obtain original source code of the method, without comments. In the issue [2976](https://github.com/INRIA/spoon/issues/2976), `setCommentEnabled(false) `was suggested. Unfortunately, it did not work for` CtMethod.getOriginalSourceFragment().getSourceCode() `as comment like `/** **/ ` still remains.

I was wondering if this is a desired behavior?

**Comment by djaekim** [comment]
Using `CtMethod.getOriginalSourceFragment().getElement()` does remove comments, but now it gives additional reference type of the object.

`@org.junit.jupiter.api.AfterEach
public void afterEach(kafka.test.ClusterConfig config) {
    org.junit.jupiter.api.Assertions.assertSame(this.config, config, "Injected objects should be the same");
}`

**Comment by djaekim** [comment]
> Using `CtMethod.getOriginalSourceFragment().getElement()` does remove comments, but now it gives additional reference type of the object.
> 
> `@org.junit.jupiter.api.AfterEach public void afterEach(kafka.test.ClusterConfig config) { org.junit.jupiter.api.Assertions.assertSame(this.config, config, "Injected objects should be the same"); }`
> 
> However, what I want is `getSourceCode()` without comments

Seems Like `prettyprint ` does exactly what I need.

**Comment by slarse** [comment]
Hi @djaekim,

There's no straightforward way to get the actual original source code without the comment, as the comment counts as part of the source code fragment corresponding to the element. This is true regardless of whether comments are included in the model or not (determined by the `setCommentsEnabled() method`).

When you call `CtElement.prettyprint()`, the element will just be pretty-printed with the default pretty-printer using the auto-import settings (which essentially just removes qualified names and adds import statements for them), so the source code will not necessarily be formatted like the original source code. In fact, if it is formatted like the original source code, that's just blind luck.

If the formatting is not crucial then just pretty-printing will work fine for your use case. If the formatting needs to be the same, I'd say the easiest thing to do would be to get the original source code and strip out any comments with a regex. I'm sure someone has already figured out an optimal regex for stripping comments from C-like source code, so that should be relatively easy.

**Comment by slarse** [comment]
Not also that for an arbitrary element `element`, then `element.getOriginalSourceFragment().getElement() == element`, it's just a roundtrip to the element itself.

**Comment by djaekim** [comment]
I see, thank you for the insight =)
