### ISSUE TITLE
Add Jenkins job with project using Java <1.5

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4128]
According to discussion in #4108, there's some binary incompatability between Java 1.5+ and Java <1.5. We should add a Jenkins job to run the normal smoke test (parse with Spoon, pretty-print, run tests) to see that we maintain compatibility with prehistoric Java code.

TODO here is for someone to point me to a publically available project that runs a Java version prior to 1.5 and I'll add a job for it on Jenkins.

**Comment by baruKreddy** [comment]
@slarse do we have any smoke test suite written already? If not provide me the URL's so that i can write the test suite.

**Comment by baruKreddy** [comment]
@slarse i would like to participate in GSoc 2022. I'm trying to contribute and fix some issues which are open to get better understanding. If there's anything missing , please correct me.

Regards
Bhargavi Reddy

**Comment by baruKreddy** [comment]
I can see its written to parse with spoon for smoke test, can you please help me or give some instructions on how to parse spoon @slarse .Thanks in Advance

**Comment by MartinWitt** [comment]
Hi @baruKreddy 

Yes, this issue is still open. You are pretty fast because I have still no confirmation that we are accepted as GSoC project. In the next days(when I/we get the confirmation) we create a new GSoC post on things you can do to get into the project spoon. For now, you can have a look at the old post from @monperrus https://github.com/INRIA/spoon/issues/3828 from 2021.

For this, specific issue, you would have to add a new java 5 or less project to the smoke tests. From my understanding you would have to add the projects here https://github.com/SpoonLabs/spoon-ci-external. Starting with an issue with a`Good First Issue` label could be way easier, for example #3923.

**Comment by slarse** [comment]
Hi @baruKreddy,

It's not entirely clear from the description I posted, but it's not possible for anyone but an integrator to actually do what needs to be done in this issue. The reason is that we don't allow outside contributors access to configure jobs on our Jenkins instance.

@MartinWitt spoon-ci-external is for running extra tasks on Spoon Core, it's not what this issue is referring to.

I've updated the issue description to be more direct.

**Comment by I-Al-Istannen** [comment]
@slarse What exactly do you mean with "runs a version < 1.5"? Just be able to compile with one? So a public java project that was built for and with java 4?

**Comment by slarse** [comment]
@I-Al-Istannen Pretty much, yes. Really, the only thing I can think of that could break is keywords (`enum` was introduced in 1.5, for example). Otherwise, Java is afaik always forward compatible.

**Comment by MartinWitt** [comment]
Is this still open? I currently try to invest some time in all the open issues.

**Comment by slarse** [comment]
It's been open for so long I think we can just close it as "not interesting enough" :)
