### ISSUE TITLE
SniperPrettyPrinter - Modifiers are printed without trailing white spaces

### ISSUE THREAD

**Issue by abhi22493** [INRIA/spoon#4220]
When using SniperPrettyPrinter, for the below input the expected output is not generated. Modifiers are printed without trailing white spaces.

Input :
```java
public class CtFieldWriteProcessor {
	
		private static final java.lang.String x;
		
		CtFieldWriteProcessor()
		{
			x = "Test";
		}
	}
```
Expected :
```java
public class CtFieldWriteProcessor {
	
		private static final int x;
		
		CtFieldWriteProcessor()
		{
			x = "Test";
		}
	}
```
Actual :
```java
public class CtFieldWriteProcessor {
	
		private static finaljava.lang.String x;
		
		CtFieldWriteProcessor()
		{
			x = "Test";
		}
	}
```
Spoon print config :
```java
launcher.getEnvironment().setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(launcher.getEnvironment()));
```

Spoon version : 9.1.0-beta-10

**Comment by nharrand** [comment]
I'm having a hard time reproducing this issue. 

Part of the problem is that, if I am not mistaken, the Java code is not syntactically correct. (The field is static and final, so it should be initialized either directly or in a static initializer bloc). And it should not be writable in the constructor. Am I missing something? 

I'm not necessarily implying, that the SniperPrettyPrinter shouldn't be able to handle syntactically incorrect code, though.

**Comment by slarse** [comment]
> Part of the problem is that, if I am not mistaken, the Java code is not syntactically correct. (The field is static and final, so it should be initialized either directly or in a static initializer bloc). And it should not be writable in the constructor. Am I missing something?

The code is _syntactically_ correct, but it is _semantically_ incorrect. JDT usually is pretty okay with semantic errors, it typically only causes problems with type resolution. I don't really see how it would cause a whitespace to be missed, that's very likely a sniper printer issue (a fairly common one, at that, the way we match up whitespace is finicky).

> In any case, can you provide the code of your transformation, because simply changing the type of the field gives me the expected output.

We have to request this from every other issue opened, it's probably about time we create an issue template.

**Comment by nharrand** [comment]
I was probably unclear. I meant that part of the problem (me not being able to reproduce the issue) was the code, and definitely not that this was the root cause of the Sniper issue.

> The code is syntactically correct, but it is semantically incorrect.

Yes, you're _technically_ correct, but it's still an error that the compiler (`javac`) rejects. ;-)
But again, it's still a bug that we should fix!

> We have to request this from every other issue opened, it's probably about time we create an issue template.

Completely agree!

**Comment by slarse** [comment]
> Yes, you're _technically_ correct, but it's still code that the compiler (`javac`) rejects. ;-) But again, it's still a bug that we should fix!

I didn't mean to be petty, it's a relatively important detail. For example, when running in noclasspath mode we accept tons of semantic errors (mostly in terms of unresolved types), but as long as the code is syntactically correct we want to be able to deal with it.

When the code is syntactically incorrect, all bets are off. Had the code actually been syntactically incorrect, and that caused the problem, then it IMO wouldn't have been a bug we should fix.

**Comment by nharrand** [comment]
No worries, I did not take it as pedentism at all. I agree that it does matter.

I used 'syntactically incorrect' as the compiler rejects it. But you are right that it is an oversimplification.
