### ISSUE TITLE
[Bug] Sniper Pretty Printer issue : Square brackets are missing in array initialization

### ISSUE THREAD

**Issue by abhi22493** [INRIA/spoon#4315]
**Describe the bug**
When sniper pretty printer writes a file, if a array initialization contains a square bracket after variable name , it removes it from the code. 

**To Reproduce**

Input:
```/*Code being processed by spoon and leading to the bug.*/
String str[] = new String[10];
```
Processing with Spoon:
```/*Code calling spoon on the input and triggering the bug.*/
launcher.getEnvironment().setPrettyPrinterCreator(() -> new SniperJavaPrettyPrinter(launcher.getEnvironment()));
```
Output:
```/*Output code or stacktrace if unexpected Exception is raised*/
String str = new String[10];
```
You can use any code to reproduce this issue as long as sniper pretty printer rewrites the file containing the above mentioned array initialization.

**Operating system, JDK and Spoon version used**

* OS: Windows
* JDK: JDK11
* Spoon version:9.1.0-beta-10

**Comment by algomaster99** [comment]
Hi!

Could you please create a pull request to introduce the failing test case? You could follow https://github.com/INRIA/spoon/pull/4289 as a template.

**Comment by algomaster99** [comment]
I found out where the issue lies. It is located in [`DefaultJavaPrettyPrinter::visitCtField`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L785) when the identifier of the field is written.

Let's consider the case of sniper printing `String str[];` (an instance of `CtFieldImpl`). Since we are printing the _no-op modfied_ field using the sniper printer, [`DefaulJavaPrettyPrinter.visitCtField`](https://github.com/INRIA/spoon/blob/12cc1a530e5801829ec4e5f674135f704040f419/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L779) will be used. We will look at two specific statements inside that method.

1. [How it prints the type](https://github.com/INRIA/spoon/blob/12cc1a530e5801829ec4e5f674135f704040f419/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L783)
2. [How it prints the identifier](https://github.com/INRIA/spoon/blob/12cc1a530e5801829ec4e5f674135f704040f419/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L785)

### How it prints the type

1. If the type of the field has _not_ been modified, the printer gets the source code from the original sources which is `String` and prints it directly.
2. If the type has been modified, it is also printed using `DJPP` and it only knows how to print it one way - only type can precede the square brackets `TYPE[]` and not the identifier.

### How it prints the identifier

The printing of token (`str` in our case) is delegated to [`SJPP.onTokenWriterWrite`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java#L218) which just prints the token and returns. This exits the process of printing the identifier even though there were two more token fragments `[` and `]` remaining.
<hr>

I propose two solutions to this.

### Workaround (it just solves the purpose of this issue)

Add a method in this [block](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java#L59-L64) so that we print **brackets** along with `printSpaces` if needed.

### Modify the metamodel

I think we should have a public API somewhere in the meta-model to check which type of declaration has been used - `int[] x` or `int x[]`. This would also fix the `toString` method and it will print `[]` depending upon the way an array has been declared.

@MartinWitt @monperrus @slarse @I-Al-Istannen what are your thoughts on this?

**Comment by MartinWitt** [comment]
The workaround looks like another band-aid on the printer. There is already a lot, so it's not the end of the world.
I prefer the clean metamodel solution, in a non-breaking way. Adding an Enum for the bracket state and some API for it should be doable. For a first fix, it's fine for me if we don't expose the bracket setting to a user. 

If we start adding printing related states to the metamodel, maybe we should mark them with some annotations? Any thoughts on this?

**Comment by algomaster99** [comment]
> The workaround looks like another band-aid on the printer.
I agree.

> Adding an Enum for the bracket state and some API for it should be doable.

I thought so too. In my head, the approach was something like this:
1. Add enum - `ArrayDeclarationKind`.
2. Configure it in `MetaModel.java`.
3. Add getters and setters in `CtArrayTypeReferenceImpl`.
4. Use the setter in `ReferenceBuilder` to set the declaration kind.

However, the batch compiler [here](https://github.com/INRIA/spoon/blob/12cc1a530e5801829ec4e5f674135f704040f419/src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java#L415) alters the declaration of the array. It changes `int array[]` to `int[] array` in the `CompilationUnitDeclaration`. That seems like a fault in the JDTBatchCompiler. Any idea how we should fix that?

**Comment by algomaster99** [comment]
@MartinWitt any idea how I can generate [`CloneVisitor.java`](https://github.com/INRIA/spoon/blob/c65b2eae4984949ca4ecc2641cc7f4052149935e/src/main/java/spoon/support/visitor/clone/CloneVisitor.java)? Since I added an enum in the metamodel, I need to regenerate it.

**Comment by MartinWitt** [comment]
https://github.com/INRIA/spoon/blob/918568ccccd2f09cb11a97840e740f701124cda2/src/test/java/spoon/processing/CtGenerationTest.java with the `CtGenerationTest`. There is a Unit test for generation and the copy command as comment.

**Comment by I-Al-Istannen** [comment]
One of the Tests in `src/test/java/spoon/processing/CtGenerationTest.java` generates it IIRC (by calling `src/test/java/spoon/generating/CloneVisitorGenerator.java`)

**Comment by algomaster99** [comment]
Got it. Thank you, both! :)

**Comment by slarse** [comment]
I'm not so sure about the idea of embedding pure formatting information in the AST. I'm not saying it's unthinkable, but it would require an overarching design decision that's a thing we do now. Historically, Spoon has been all about keeping irrelevant details out of the AST.

**Comment by algomaster99** [comment]
> Historically, Spoon has been all about keeping irrelevant details out of the AST.

That makes sense. If printing details were also stored in the AST, we would never need a sniper printer.

I haven't thought about any other solutions. The most convenient way (unsure if it's the ideal) seems to store this information in the AST. I will submit a pull request based on this solution. Let's see what everyone has to say about it.

**Comment by slarse** [comment]
One potential solution would be to store it as metadata on the node. In some sense this is metadata, after all.

Is it possible to see from the JDT node where the brackets are located? Or have you figured out some other way of determining their position? Otherwise, I think this will require inspecting the raw source code, and that we can just as well do just prior to, or in conjunction with, pretty-printing.

**Comment by algomaster99** [comment]
@slarse I used two attributes in `ArrayTypeReference` - `sourceStart` and `sourceEnd`. I found their difference and if it was lesser than `ArrayTypeReference.toString().length`, there has to be more than one `[]` after the variable name. 

However, this was not giving right results when perfomed for array declaration such as - `int[][] x[][]`.

We can try parsing the raw source code as well. It's a bit tough to write that method accurately though, surely not impossible.

**Comment by slarse** [comment]
Both of those are to some extent inspecting the source code, just different attributes of it.

It's in my experience very uncommon to write the square brackets after the variable name in Java, and writing brackets both after the type and variable name is something I've never seen, and have a hard time imagining would be written in a serious project.

The case `int[][] x[][]` I think we can pretty safely ignore, I don't think we'll ever encounter it, and if we do it will be on very rare occasions.

For `int x[]` we need to ensure that the correct amount of square brackets are printed, but as this is an uncommon style I don't think it's worthwhile to put too much time into ensuring the brackets are in the correct place.

**Comment by algomaster99** [comment]
> It's in my experience very uncommon to write the square brackets after the variable name in Java, and writing brackets both after the type and variable name is something I've never seen, and have a hard time imagining would be written in a serious project.

I agree with both of these statements. We only spotted the first case [here](https://github.com/SpoonLabs/sorald/issues/603#issuecomment-908562319).

> For int x[] we need to ensure that the correct amount of square brackets are printed, but as this is an uncommon style I don't think it's worthwhile to put too much time into ensuring the brackets are in the correct place.

As a first step, we should just ensure that the output is compilable and I think that would be possible if analyse the source code while pretty-printing. Modifying the meta-model would be overkill.
