### ISSUE TITLE
Push patch versions to maven central instead of uploading SNAPSHOTs to nexus repository manager

### ISSUE THREAD

**Issue by algomaster99** [INRIA/spoon#4319]
I wanted to have a discussion on how we release Spoon artefacts. Currently, we only release major and minor version upgrades which are evident from [here](https://github.com/INRIA/spoon/releases). The patch version is released every time something is pushed to `master`, but it is uploaded to https://repository.ow2.org/nexus/content/repositories/snapshots/fr/inria/gforge/spoon/spoon-core/. I wanted to know why do we upload it there instead we can directly upload it to maven central. If someone has to use Spoon's SNAPSHOT version, they have to add the following XML snippet into their `pom` file.
```xml
<repositories>
  <repository>
    <id>spoon-snapshot</id>
      <name>Maven Repository for Spoon Snapshots</name>
      <url>https://repository.ow2.org/nexus/content/repositories/snapshots/</url>
  </repository>
</repositories>
```
I think the better alternative for patch versions would be to directly upload them to maven central for two reasons:
1. All the releases can be found in one place - maven central.
2. Users can just change the version number of Spoon and use the latest versions.

I saw `beta` versions of Spoon on [Maven central](https://repository.ow2.org/nexus/content/repositories/snapshots/fr/inria/gforge/spoon/spoon-core/), but I don't think so they are released as often and I don't know what triggers them.

**Comment by slarse** [comment]
We upload to the OW2 Nexus as Spoon is part of the OW2 consortium, and a requirement is to have source code there. Actually, if we ever want to move past the incubation stage, we need to at least sync all releases there as well.

We only release a patch version if there's something critical to address that cannot wait until the next minor release. Patch versions come with some amount of overhead, as they require us to create a maintenance branch for the concerned minor release and patch and release from there, and then ensure we sync that back to master. We don't have any automation in place to handle that, so it's much easier for us to just stick to minor releases.

It is worth considering separating maintenance from feature work, also in the spirit of moving past the incubation stage of OW2. But it's a lot of overhead, @monperrus what do you think?

Also note that a SNAPSHOT version is not at all the same as a patch version, and should in general never be used outside of just testing stuff out. If you specify e.g. `10.1.0-SNAPSHOT` as the version in your POM file, then you'll pull the latest snapshot every time there's been a new push to Spoon's master branch. That's very undesirable for any dependent system.

> I saw beta versions of Spoon on Maven central, but I don't think so they are released as often and I don't know what triggers them.

Beta versions are supposed to be released every weekend, but it's been a month since the last release. @monperrus I think the beta deployments aren't working.

**Comment by algomaster99** [comment]
Thanks for the answer! Closing this.

**Comment by MartinWitt** [comment]
> Beta versions are supposed to be released every weekend, but it's been a month since the last release. @monperrus I think the beta deployments aren't working.

As @slarse said, we don't have a new version on central since 8.12.2021. Is the script defect, or is this on purpose?

**Comment by monperrus** [comment]
yes, this is https://github.com/INRIA/spoon/issues/3890
