### ISSUE TITLE
lsif extraction breaks the build

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4407]
LSIF extraction breaks the build, see recent commit statuses incl. https://github.com/INRIA/spoon/runs/4727158822?check_suite_focus=true

@rvantonder WDYT?

**Comment by rvantonder** [comment]
Ah, we've since transitioned to LSIF indexing using a different toolchain. The current action seems to no longer work, so I suggest removing it. It's possible to restore LSIF support for this repository with the new toolchain but I won't be going ahead to make those changes. Instead, if you're interested in that, see details here:

https://about.sourcegraph.com/blog/java-scala-kotlin-code-intelligence/?utm_medium=social&utm_source=twitter&utm_campaign=blog

https://sourcegraph.github.io/lsif-java/docs/getting-started.html

**Comment by monperrus** [comment]
Thanks a lot @rvantonder 

It seems that lsif-hava does not use Spoon anymore (https://github.com/sourcegraph/lsif-java/blob/main/build.sbt).

What AST library do you use now?
