### ISSUE TITLE
MavenLauncherTest fails on Windows - can't delete temporary directory

### ISSUE THREAD

**Issue by slarse** [INRIA/spoon#4877]
Out of the blue, one of the MavenLauncher tests just started failing on Windows with this error message:

```
Error:  Errors: 
Error:    MavenLauncherTest.spoonMavenLauncherTest(Path) � IO Failed to delete temp directory C:\Users\RUNNER~1\AppData\Local\Temp\junit13011363813463001138. The following paths could not be deleted (see suppressed exceptions for details): , src, src\test, src\test\resources, src\test\resources\maven-launcher, src\test\resources\maven-launcher\java-11
```

See https://github.com/INRIA/spoon/runs/8101496901?check_suite_focus=true

**Comment by I-Al-Istannen** [comment]
I remember @MartinWitt cursing about that a while ago in a project of his. I think something is continuing to hold a file handle and windows has *mandatory* file locks…

That lines up with
```
	Suppressed: java.nio.file.FileSystemException: C:\Users\RUNNER~1\AppData\Local\Temp\junit13011363813463001138\src\test\resources\maven-launcher\java-11: The process cannot access the file because it is being used by another process.
```

So I guess to properly fix this, we need to find the part in spoon that keeps resources open it probably should not.

**Comment by I-Al-Istannen** [comment]
@MartinWitt, @SirYwell and I had a closer look and we have absolutely no clue. All profiling inspections found no leftover open files in the temp folder, I do not see any on Linux, the spoon code paths touching files there use try-with-resources, …

The error is also not reproducible locally and the CI now runs to completion on master.

Feels like
![grafik](https://user-images.githubusercontent.com/20284688/187694524-c6204a4a-61fa-49f6-b4d0-45069d0b8ea8.png)
(https://xkcd.com/378/)

**Comment by slarse** [comment]
Let's just silently pretend like this didn't happen consistently for two days and diagnose it as "dammit, Windows"

**Comment by I-Al-Istannen** [comment]
Okay, sadly this is still happening and I can reproduce it locally. Adding a slow sleep after the test makes the test a lot less likely to fail and sleeping for a longer period seems to resolve it.

Adding an exception breakpoint, waiting for it to be hit and then continuing the program also reliably works. As the JVM shouldn't do too much while it is paused at a breakpoint, I am no longer so sure that spoon itself is causing the file handle to be kept open. Maybe the spawned maven process instead keeps it open for a small duration after the `waitFor` method returns?

[StackOverflow](https://stackoverflow.com/a/2523880) seems to suggest that freeing the locks after a process exits (iff the process does not properly clean up itself), might **take multiple seconds** and is not done instantly. This *could* explain the behaviour here.

In that case, we can't really do anything as far as I can tell except artifically sleeping for a bit and praying. WDYT @slarse?

**Comment by slarse** [comment]
Dammit, Windows.

@I-Al-Istannen While that idea of yours would work, it's a bit inconvenient to have to have that in every test class. I'm thinking we could sprinkle some magic fairy dust here and designate a "workspace" directory that is created before each test and torn down after each test. Possibly the very easiest thing would be to actually use the `spooned` directory and register a listener to clean it up before each test ([here's an example of a listener I implemented a long time ago](https://github.com/SpoonLabs/sorald/blob/master/sorald/src/test/java/sorald/SystemExitHandler.java)). This would have the added benefit of removing the test inderdependencies that already exist due to using the spooned directory.

The _before_ is important, because not only does it cover the case of incorrect cleanup before a test runs, but I believe we also have some code generation implemented as tests. Thoughts?

**Comment by I-Al-Istannen** [comment]
> Dammit, Windows.

Martin or Hannes can debug the next bug of this kind… :P God that was annoying (and there still is a small chance this is not the root cause).

----

Well, it would only be needed in classes actually spawning other processes — that doesn't make it much better though.

It seems that exceptions in execution listeners do not cause test failures (https://github.com/junit-team/junit5/issues/1777). This is probably okay, but good to keep in mind when debugging weird errors.

I was looking for something like this a while ago and didn't find anything that works without explicit registration. TIL Junit actually makes proper use of the service loader API. Sounds good to me.

We probably want a constant for the temp directory, but we need a way to refer it from other tests without blindly hardcoding `spooned` everywhere. I quickly whipped something up exposing a static `Path TEMPDIR` and it seems to work alright, though I haven't tested it on Windows yet. I will open a PR and then we can tear it to shreds?

> but I believe we also have some code generation implemented as tests

I believe that generates into `target/generated`, but I agree with the general pattern nevertheless. It's nice to be able to peek at stuff ~~if~~ *when* it explodes.
