### ISSUE TITLE
Install Sonatype Lift on Spoon repo

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4918]
FYI, we're installing the security analysis tool [Sonatype Lift](https://lift.sonatype.com/) on the repo.

**Comment by MartinWitt** [comment]
If we upgrade in the field of security, how about https://snyk.io/? Snyk is a tool from RedHat like dependent bot telling us our security crimes. More static analysis should never harm.
Example:
![image](https://user-images.githubusercontent.com/25300639/192225666-2308fe64-e85d-4bcb-805e-9b974b423480.png)

**Comment by monperrus** [comment]
Great idea, I'm in favor of installing Snyk too.

**Comment by monperrus** [comment]
FTR, the dashboard is at https://lift.sonatype.com/results/github.com/INRIA/spoon

**Comment by slarse** [comment]
> More static analysis should never harm.

@MartinWitt Research would tell otherwise, noise from static analysis tools is one of the larger reasons as to why devs dislike or just ignore static analysis tools. I'm too lazy to grab primary sources for that claim but [this paper where at least one of the coauthors is just the best](https://arxiv.org/pdf/2103.12033.pdf) is a _tremendous_ secondary source :)

On a somewhat serious note, excessive amounts of static analysis output is bothersome. If it's not in your face in a PR it won't be acted upon, but if it is in your face in a PR it needs to be... not excessive. It's a balancing act, where too much is definitely a thing.

> FTR, the dashboard is at https://lift.sonatype.com/results/github.com/INRIA/spoon

@monperrus Guessing that is locked behind a login, I get a 404.

**Comment by monperrus** [comment]
and if you sign in with your Github account?

**Comment by monperrus** [comment]
FYI: the list of Lift static analyzers is at https://help.sonatype.com/lift/included-analyzers

cc/ @fermadeiral

**Comment by MartinWitt** [comment]
Just as a heads-up, spoon is accepted in the Snyk open-source program. This gives us more or less any enterprise features we want, like unlimited scans and more. I will provide more information as soon as I get more from them.

**Comment by monperrus** [comment]
excellent!
