### ISSUE TITLE
NoSourcePosition error

### ISSUE THREAD

**Issue by zqudm** [INRIA/spoon#4926]
When i use spoon-core-6.0.0-jar-with-dependencies.jar, my program works well. However, when i use spoon-core-9.2.0-beta-8-jar-with-dependencies.jar, a failure occurred, that is,

_Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit
at spoon.reflect.cu.position.NoSourcePosition.getSourceEnd(NoSourcePosition.java:67)_

How to fix this error? Thanks !

**Comment by algomaster99** [comment]
Hi @zqudm !

It is quite difficult to tell what broke in the earlier version because it is too old. You could try to manually find it here - https://github.com/INRIA/spoon/compare/spoon-core-6.0.0...spoon-core-10.0.0. Or I suggest that you provide us with more details like what exactly did you try to run? Some sample source code.

**Comment by slarse** [comment]
@zqudm Please use the Bug issue template if you consider this a bug, it prompts you for all of the information you need to provide for us to be able to analyze your problem.
