### ISSUE TITLE
Spoon on untrusted code

### ISSUE THREAD

**Issue by monperrus** [INRIA/spoon#4945]
@I-Al-Istannen writes in https://github.com/INRIA/spoon/pull/4943#issuecomment-1268599888

> As an aside, formulating some kind of "never run spoon on untrusted code" (or can you?) policy might also be an interesting thing. I am not sure in what contexts spoon is mostly used. I had a few where I absolutely did not trust the code I analyzed but I would have sandboxed the whole thing away.

**Comment by monperrus** [comment]
I'd say that if you analyze only Java source code, there is no risk.

My understanding is that the security problems start when:

* one provides some jar files as Spoon classpath
* one calls `compile()` or `newInstance()` and `getActualClass()`

**Comment by I-Al-Istannen** [comment]
Okay, I was trying to write a small exploit and noticed a few things:

1. spoon emits class files in a different folder than I thought by default
2. the input classloader has no url path by default. This prevents attacks which ship a .class file in the same folder as source code.
3. the compilation takes place *after* model building

Due to this, I believe spoon is quite safe in its *default* configuration. There is no way I can see to load a class compiled from your model unless you manually change the configuration. There is one vulnerable place but that requires the input classloader to overlap with the source code directory. The new javadoc for getActualClass is probably still fine: If you don't know how the pieces interact you should better not touch it when running it on untrusted code.

So your understanding is correct and actually a bit too conservative (I *think*). Calling any of those methods is fine, as long as you do not change the input class loader or default binary output path. It also means that you *need* to have classes on the classpath in normal operation, as the classes Spoon compiled are inaccessible by default (which is quite sane!).

I might try to write a small CTF challenge involving this if I find the muse, but I currently don't see any large risks in spoon. This is of course never an absolute statement, but the situation is less bad than I thought before.

**Comment by slarse** [comment]
Just on the note of actually finding a vulnerability, please follow the security policy and create a security advisory to discuss it behind closed doors. I think only @monperrus has the necessary permissions to create one at this time.

**Comment by I-Al-Istannen** [comment]
That's fair, but based on my understanding of the JLS and the contract of the reflection methods, you actually *have to try quite hard* to get it to execute code. In particular, class [linking](https://docs.oracle.com/javase/specs/jls/se19/html/jls-12.html#jls-12.3) is currently deferred by spoon until an instance is created (or any of the other conditions in [12.4.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-12.html#jls-12.4.1) are hit.

This *should* result in even calling `getActualClass` on untrusted code *not being an issue*, but it is quite easy to cause arbitrary code to execute depending on what you do with the resulting class. The whole mechanism seems sounder than I initially thought, the java reflection API has some pretty restricting defaults. I wonder whether that warrants adjusting the Javadoc in #4943 to not be quite as bleak.

If I do find anything to bypass it which is not me *deliberately* setting up a weird situation, I will follow the disclosure procedures :) At the current point in time I don't think that's easily possible though. But as with all things security, they seem impossible until they aren't.

**Comment by slarse** [comment]
> If I do find anything to bypass it which is not me deliberately setting up a weird situation, I will follow the disclosure procedures :)

That's what I meant :)
