### ISSUE TITLE
[Question] Is there a reason theres no CtFinally?

### ISSUE THREAD

**Issue by brandy007** [INRIA/spoon#5012]
While working on a processor to check if a statement is within a finally block, i noticed that there is a CtTry and a CtCatch but no CzFinally. Is there a specific reason for this?

Regards

**Comment by SirYwell** [comment]
Hi,
the `finally` part is only a simple block (plus the `finally` keyword. This is represented by https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/code/CtTry.html#getFinalizer() in spoon. The name might be a bit confusing...

`CtTry` and `CtCatch` store additional information (`CtTry` stores the catch blocks and the finally block additionally to the try block, also it can have resources, etc, a catch block introduces local variables...), that's why they have their own dedicated AST elements.

**Comment by brandy007** [comment]
thanks for the clarification.
