### ISSUE TITLE
【Question】：Is there a good way to solve the problem of duplicate package names

### ISSUE THREAD

**Issue by honghao12** [INRIA/spoon#5316]
**Analysis code repository:** https://github.com/INRIA/spoon.git

**Location of the problem：**
![image](https://github.com/INRIA/spoon/assets/51260721/3c7a68a5-92e5-44f6-b483-231b47c328b9)

**ERROR:**
```
Ambiguous package name detected. If you believe the code you analyzed is correct, please file an issue and reference https://github.com/INRIA/spoon/issues/4051. Error details: Found 2 non-empty packages with name 'spoon.visualisation.instrument'
```

**version:**
10.3.0

**Comment by I-Al-Istannen** [comment]
The problem is that this whole thing is not well defined. What do you *expect* the model to look like?

I see two (three) possible ways forward here:
1. Coalesce the two packages into one. I am not sure how easy this is and it *will* have very weird consequences when two actual java modules share a middle package (though one of them needs to be empty, otherwise they would overlap. But it can still have subpackages, e.g. `foo.bar.Baz` in `A` and `foo.bar.sub.Baz` in `B`)
2. Randomly pick one package to return (makes your queries non-deterministic and/or potentially wrong)
3. Heuristically pick a package to return (e.g. prefer src over test if you have a path)

Which one of those would you find the most natural? The code you gave spoon is not really well-formed (you need a build system to massage it), so spoon can only approximate here.

**Comment by I-Al-Istannen** [comment]
Hey, feel free to reopen, if you have a need or a preference for one of the options. As far as I can tell Spoon is behaving correctly, the question is mostly how to handle common invalid situations in the wild.
