### ISSUE TITLE
Release Spoon 5.2.0 

### ISSUE THREAD

**Issue by GerardPaligot** [INRIA/spoon#725]
We'll release the version Spoon 5.2.0 Wednesday, June 28.

Think to test the snapshot version to detect any bug or regression between the version 5.1.1 and the new one 5.2.0.

[Changelog here](https://github.com/INRIA/spoon/issues/725#issuecomment-228414886). Thanks to @tdurieux

**Comment by tdurieux** [comment]
The auto-generated changelog

# New feature

* **annotation** : Reference to an annotation field as an invocation. (PR: #660)
* **ast** : Clean reset of collections in intercession methods. (PR: #712)
* **checks** : Disable AST checks. (closes #649). (Issue: #649) (PR: #684)
* **comment**
  * All comments are handled by the same option (-c). (Issue: #666) (PR: #676)
  * Adds comment support. (PR: #554)
* **factory** : Creates factory methods for primitives. (Issue: #651) (PR: #700)
* **filter** : Adds LineFilter to reason about statements in blocks. (PR: #678)
* **model** : All setters allow null parameters. (PR: #694)
* **shadow** : Build shadow elements using Reflection API. (PR: #569)


# Fixes

* Declaring type OR package should be set for a reference, not both. (PR: #613)
* Annotation values traversal should be delegated to scan(), fixes #603. (Issue: #603) (PR: #614)
* Fix bug introduced in #689 (order to iterate with a Deque and Stack are different). (Issue: #689) (PR: #710)
* Fix bugs in ImportScannerImpl. (PR: #596)
* Fix a number of bugs related to handling of unnamed packages. (PR: #705)
* Fix nullpointer in hasTypeInImports. (PR: #672)
* Use CtTypeParameterRef for formal ops. (PR: #620)
* Doesn't warn for implicit source code. (PR: #696)
* Fix many small bugs with double usage of AST nodes in different subtrees,. (PR: #645)
* Fix bugs in ClassFactory.create() methods. (PR: #610)
* Fix a bug in CodeFactory.createThisAccess() (target was not set). (PR: #612)
* Fix bugs with creating CtTypeAccess without cloning reference, that leads to problems with replace() in graph. (PR: #611)
* **ast** : Align CtNewClass with CtConstructorCall. (PR: #595)
* **cache** : Invalidate cache of the compiler. (Issue: #575) (PR: #577)
* **comment** : Fix bug in the usage of the new flag (closes #721). (Issue: #721) (PR: #723)
* **compiler** : Add class generated to compilation unit. (PR: #564)
* **conditional** : Puts parenthesis when it is necessary. (PR: #669)
* **doc** : Handles comments in CtNewArray and in CtConditional. (Issue: #588) (PR: #590)
* **factory** : Gets inner type from Class/InterfaceFactory. (closes #640). (Issue: #640) (PR: #682)
* **filter** : Fixes NPE in VariableAccessFilter when the getVariable() is null (e.g. super). (PR: #641)
* **getparent** : GetParent(Filter) does not return the current element when it matches the filter. (PR: #638)
* **lambda** : Builds executable ref from a lambda. (PR: #665)
* **noclasspath** : NPE in a scope usage. (Issue: #574) (PR: #576)
* **parent**
  * HasParent should not  always return false. (PR: #686)
  * Avoid NPE with CtElement#hasParent(CtElement) (Closes #679). (Issue: #679) (PR: #685)
* **performance** : Rewrite CtExecutableReference#isOverriding. (Issue: #586) (PR: #592)
* **printer** : Protects each getParent invocation in DefaultJavaPrettyPrinter. (PR: #704)
* **ref** : Scan declaring type for CtExecutableReference. (PR: #715)
* **unbox** : Don't throw a SCNFException with #unbox(). (PR: #620)


# Documentation

* **executable** : Specify executable returns by getAllExecutables. (PR: #655)
* **gradle** : Updates spoon repository. (PR: #720)
* **target** : Specify behavior of CtTargetedExpression#getTarget. (PR: #653)
* **version**
  * Upgrade to 5.1.1. (PR: #720)
  * Updates documentation to Spoon 5.1.0. (PR: #564)
* Fix typos and improves documentation. (PR: #587)

# Refactoring

* CtFormalTypeDeclarer/CtActualTypeContainer, improves CtInvocation. (PR: #656)
* Move generation tests (Closes #711). (Issue: #711) (PR: #724)
* Throws a SpoonException when we set ? in CtTypeRef. (PR: #635)
* Refactors and fixes test code. (PR: #642)
* Switch all usages of Stack to Deque. (PR: #698)
* Refactoring of CtElement.equals for performance. (PR: #674)
* **api**
  * Changes generics bounds from List to Set. (PR: #659)
  * Uses actual types of executable ref in constructor call. (PR: #654)
  * Invalidate always the cache of JDT compiler. (PR: #577)
  * CtGenericElement.formalTypeParameters use CtTypeParameterRef. (Issue: #580) (PR: #595)
  * Handles null and empty list for setBounds(List). (Issue: #593) (PR: #594)
* **clone**
  * Adds the handy CtElement#clone (and deprecates CoreFactory#clone). (PR: #677)
  * Creates CloneVisitor that is generated. (PR: #717)
* **factory** : AnnotationFactory's factory methods to use more references. (PR: #713)


# Performance

* Performance improvements for replace and substitution. (PR: #709)


# Tests

* Test generics in constructor call. (PR: #595)
* **compile** : Compile generated java file. (PR: #564)


# Other

* **appveyor** : Adds a proxy to download dependency. (PR: #657)
* **java** : Drop Java 6 compatibility for Java 7. (PR: #699)
* **jdt** : Updates JDT version and repo. (PR: #695)
* **roadmap** : Adds task about generics in the roadmap. (PR: #652)


# Unknow

* Added myself as a contributor (as requested). (PR: #619)
* Merge branch 'stable'. (PR: #720)
* Prepare release spoon-core-5.1.1. (PR: #720)
* Updates remote repository to download JDT. (PR: #703)
* Remove CtImplicitTypeRef and CtImplicitArrayTypeRef. (PR: #667)
* Improves model built by Java reflection. (PR: #658)
* Minor fixes to DefaultJavaPrettyPrinter. (PR: #648)
* Make CtElementImpl.emptyList() and emptySet() DIFFERENT objects because otherwise they cannot conform both java.util.List and java.util.Set equals()/hashCode() contract; never use Collections.unmodifiableCollection() (if wrapping list or set) because it narrows possible use on the client side without actual need; try to avoid creating unmodifiableList/Set(children) wrapper when the wrapped children is already an empty collection. (PR: #647)
* A faster implementation of 'replace' based on code generation. (PR: #632)
* More documentation about Spoon's runtime reflection. (PR: #625)
* Improves pretty-printer formatting so that it's compatible with Checkstyle. (PR: #634)
* Introduces CtModel for #584. (Issue: #584) (PR: #589)
* Prepare for next development iteration. (PR: #720)
* Optimize CtArrayTypeReferenceImpl.getSimpleName() and getQualifiedName() methods (don't use reflection on each call). (PR: #617)
* Don't rely on ClassCastException as normal control flow, i. e. avoid frequent throws of ClassCastException, because it is expensive in JVM. (PR: #615)
* Optimize comments list in CtElementImpl. (PR: #609)
* Optimize partial traversals (local variable and exception variable search in JDTTreeBuilder, nested type search in CtTypeImpl). (PR: #608)
* Optimize SortedList.add(). (PR: #607)
* Add missing scanning of CtExecutionReference's parameters in CtScanner. (PR: #601)
* Optimize CtElement.equals(). (PR: #591)
* Use the same logic in DefaultJavaPrettyPrinter.visitCtTypeReference() and visitCtTypeReferenceWithoutGenerics(). (PR: #585)
* Add a point in the roadmap (build model of binary code using a decompiler). (PR: #571)
* Adds documentation for template matchers. (PR: #568)
* Prepare for next development iteration. (PR: #564)
* Prepare release spoon-core-5.1.0. (PR: #564)

**Comment by tdurieux** [comment]
I updated the changelog with the today PR

**Comment by GerardPaligot** [comment]
First release done by our [Jenkins](https://ci.inria.fr/sos/view/Controller/job/Release%20Deployer/51/)! \o/

**Comment by GerardPaligot** [comment]
@monperrus What do you think about this changelog?

# AST changes

* **java** : Drop Java 6 compatibility for Java 7. (PR: #699)
* **ast**
	* Clean reset of collections in intercession methods. (PR: #712)
	* All setters allow null parameters. (PR: #694)
	* Introduces CtModel for #584. (Issue: #584) (PR: #589)
* **factory** : Creates factory methods for primitives. (Issue: #651) (PR: #700)
* Switch all usages of Stack to Deque. (PR: #698)
* Remove CtImplicitTypeRef and CtImplicitArrayTypeRef. (PR: #667)

# New feature

* **shadow** : Build shadow elements using Reflection API. (PR: #569)
* **checks** : Disable AST checks. (Issue: #649) (PR: #684)
* **comment**
  * All comments are handled by the same option (-c). (Issue: #666) (PR: #676)
  * Adds comment support. (PR: #554)
* **filter** : Adds LineFilter to reason about statements in blocks. (PR: #678)
* **clone** : Adds the handy CtElement#clone (and deprecates CoreFactory#clone). (PR: #677)
* Refactoring of CtElement.equals for performance. (PR: #674)
* A faster implementation of 'replace' based on code generation. (PR: #632)

# Fixes

* **annot** : Reference to an annotation field as an invocation. (Issue: #578) (PR: #660)
* **ast** : Align CtNewClass with CtConstructorCall. (PR: #595)
* **cache** : Invalidate cache of the compiler. (Issue: #575) (PR: #577)
* **clone**
  * Scan declaring executable of CtParameterRef (closes #729). (Issue: #729) (PR: #730)
  * Fix bug (modifiers not deep copied). (PR: #727)
* **comment** : Fix bug in the usage of the new flag (closes #721). (Issue: #721) (PR: #723)
* **compiler** : Add class generated to compilation unit. (PR: #564)
* **conditional** : Puts parenthesis when it is necessary. (PR: #669)
* **doc** : Handles comments in CtNewArray and in CtConditional. (Issue: #588) (PR: #590)
* **factory** : Gets inner type from Class/InterfaceFactory. (closes #640). (Issue: #640) (PR: #682)
* **filter** : Fixes NPE in VariableAccessFilter when the getVariable() is null (e.g. super). (PR: #641)
* **getparent** : GetParent(Filter) does not return the current element when it matches the filter. (PR: #638)
* **lambda** : Builds executable ref from a lambda. (PR: #665)
* **noclasspath** : NPE in a scope usage. (Issue: #574) (PR: #576)
* **parent**
  * Avoid NPE with CtElement#hasParent(CtElement) (Closes #679). (Issue: #679) (PR: #685)
  * HasParent should not  always return false. (PR: #686)
* **performance** : Rewrite CtExecutableReference#isOverriding. (Issue: #586) (PR: #592)
* **printer** : Protects each getParent invocation in DefaultJavaPrettyPrinter. (PR: #704)
* **ref** : Scan declaring type for CtExecutableReference. (PR: #715)
* **unbox** : Don't throw a SCNFException with #unbox(). (PR: #620)
* Declaring type OR package should be set for a reference, not both. (PR: #613)
* Annotation values traversal should be delegated to scan(), fixes #603. (Issue: #603) (PR: #614)
* Fix bugs in ImportScannerImpl. (PR: #596)
* Fix a number of bugs related to handling of unnamed packages. (PR: #705)
* Fix bug introduced in #689 (order to iterate with a Deque and Stack are different). (Issue: #689) (PR: #710)
* Fix nullpointer in hasTypeInImports. (PR: #672)
* Use CtTypeParameterRef for formal ops. (PR: #620)
* Fix bugs in ClassFactory.create() methods. (PR: #610)
* Fix many small bugs with double usage of AST nodes in different subtrees,. (PR: #645)
* Doesn't warn for implicit source code. (PR: #696)
* Fix a bug in CodeFactory.createThisAccess() (target was not set). (PR: #612)
* Fix bugs with creating CtTypeAccess without cloning reference, that leads to problems with replace() in graph. (PR: #611)

**Comment by monperrus** [comment]
I've directly updated this thread. that's fine.

**Comment by GerardPaligot** [comment]
Changelog attached to the release and release announced on the mailing list.
